using System.Collections.Generic;

namespace PdiVault;

/// <summary>
/// App-chrome localization: nav names and the most common actions, in every
/// language the backend supports. PDI's explanatory notes are localized
/// server-side by the tenant's language setting; this table covers the frame
/// around them. Missing keys fall back to English.
/// </summary>
public static class L10n
{
    /// <summary>
    /// The language of somebody who has no account to take one from.
    ///
    /// <para><c>AppState.Language</c> is the stored setting and is "en" until
    /// an account exists. Every sentence the backend composes on a public
    /// route is chosen from <c>Accept-Language</c>, and this shell was sending
    /// no such header — Windows has been carrying the answer in
    /// CurrentUICulture the whole time.</para>
    ///
    /// <para>Region dropped; anything this app does not carry falls back to
    /// English rather than guessing.</para>
    /// </summary>
    public static readonly string[] Supported =
        { "en", "es", "fr", "de", "pt", "it", "ja", "zh", "hi", "ar" };

    public static string DeviceLanguage()
    {
        var culture = System.Globalization.CultureInfo.CurrentUICulture;
        while (culture != null && !string.IsNullOrEmpty(culture.Name))
        {
            var code = culture.TwoLetterISOLanguageName.ToLowerInvariant();
            if (System.Array.IndexOf(Supported, code) >= 0) return code;
            culture = culture.Parent;
        }
        return "en";
    }

    /// <summary>The shell's chrome, in the signed-in account's language.
    ///
    /// <para>Convenient and, on a public surface, wrong: the language it
    /// reaches for is <c>AppState.Current.Language</c>. A reader with no
    /// account is answered in English no matter what their machine is set to,
    /// and does it without the screen ever naming the setting. iOS and Android
    /// cannot make that mistake — both of their <c>t</c> functions require the
    /// language as an argument.</para></summary>
    public static string T(string key) => T(key, AppState.Current.Language);

    /// <summary>The same table, asked in a language the caller names. Pass
    /// <c>DeviceLanguage()</c> on any surface whose reader has no
    /// account.</summary>
    public static string T(string key, string lang)
    {
        if (Table.TryGetValue(key, out var row))
            return row.TryGetValue(lang, out var s) ? s
                 : row.TryGetValue("en", out var en) ? en : key;
        return key;
    }

    private static readonly Dictionary<string, Dictionary<string, string>> Table = new()
    {
        ["fb.sofar"] = new() { ["en"] = "So far: {list}", ["es"] = "Hasta ahora: {list}", ["fr"] = "Jusqu'ici : {list}", ["de"] = "Bisher: {list}", ["pt"] = "Até agora: {list}", ["it"] = "Finora: {list}", ["ja"] = "これまで：{list}", ["zh"] = "目前：{list}", ["hi"] = "अब तक: {list}", ["ar"] = "حتى الآن: {list}" },
        ["fb.thanks"] = new() { ["en"] = "Thank you — sent.", ["es"] = "Gracias, enviado.", ["fr"] = "Merci — envoyé.", ["de"] = "Danke — gesendet.", ["pt"] = "Obrigado — enviado.", ["it"] = "Grazie — inviato.", ["ja"] = "ありがとうございます — 送信しました。", ["zh"] = "谢谢 — 已发送。", ["hi"] = "धन्यवाद — भेज दिया गया।", ["ar"] = "شكرًا لك — تم الإرسال." },
        ["nadm.rotated"] = new() { ["en"] = "Rotated — every record re-sealed under the new version.", ["es"] = "Rotada: todos los registros se han vuelto a sellar con la nueva versión.", ["fr"] = "Rotation effectuée — tous les enregistrements ont été rescellés sous la nouvelle version.", ["de"] = "Rotiert — jeder Datensatz wurde unter der neuen Version neu versiegelt.", ["pt"] = "Rodada — todos os registos foram novamente selados sob a nova versão.", ["it"] = "Ruotata — ogni record è stato risigillato con la nuova versione.", ["ja"] = "ローテーションしました — すべてのレコードを新しいバージョンで再封印しました。", ["zh"] = "已轮换 — 所有记录已在新版本下重新封存。", ["hi"] = "घुमाई गई — हर रिकॉर्ड नए संस्करण के तहत पुनः सील किया गया।", ["ar"] = "تم التدوير — أُعيد ختم كل سجل بالإصدار الجديد." },
        ["nfil.content"] = new() { ["en"] = "Content", ["es"] = "Contenido", ["fr"] = "Contenu", ["de"] = "Inhalt", ["pt"] = "Conteúdo", ["it"] = "Contenuto", ["ja"] = "内容", ["zh"] = "内容", ["hi"] = "सामग्री", ["ar"] = "المحتوى" },
        ["nfil.content.ph"] = new() { ["en"] = "the file body to seal", ["es"] = "el cuerpo del archivo a sellar", ["fr"] = "le corps du fichier à sceller", ["de"] = "der zu versiegelnde Dateiinhalt", ["pt"] = "o corpo do ficheiro a selar", ["it"] = "il corpo del file da sigillare", ["ja"] = "封印するファイル本文", ["zh"] = "要封存的文件正文", ["hi"] = "सील करने हेतु फ़ाइल सामग्री", ["ar"] = "محتوى الملف المراد ختمه" },
        ["nfil.filename"] = new() { ["en"] = "Filename", ["es"] = "Nombre de archivo", ["fr"] = "Nom du fichier", ["de"] = "Dateiname", ["pt"] = "Nome do ficheiro", ["it"] = "Nome del file", ["ja"] = "ファイル名", ["zh"] = "文件名", ["hi"] = "फ़ाइल नाम", ["ar"] = "اسم الملف" },
        ["nfil.filename.ph"] = new() { ["en"] = "e.g. results.pdf", ["es"] = "p. ej. resultados.pdf", ["fr"] = "ex. resultats.pdf", ["de"] = "z. B. ergebnisse.pdf", ["pt"] = "p. ex. resultados.pdf", ["it"] = "es. risultati.pdf", ["ja"] = "例：results.pdf", ["zh"] = "例如：results.pdf", ["hi"] = "उदा. results.pdf", ["ar"] = "مثال: results.pdf" },
        ["nfil.programs"] = new() { ["en"] = "Programs", ["es"] = "Programas", ["fr"] = "Programmes", ["de"] = "Programme", ["pt"] = "Programas", ["it"] = "Programmi", ["ja"] = "プログラム", ["zh"] = "合规方案", ["hi"] = "कार्यक्रम", ["ar"] = "البرامج" },
        ["nfil.recipient"] = new() { ["en"] = "Recipient", ["es"] = "Destinatario", ["fr"] = "Destinataire", ["de"] = "Empfänger", ["pt"] = "Destinatário", ["it"] = "Destinatario", ["ja"] = "受取人", ["zh"] = "接收人", ["hi"] = "प्राप्तकर्ता", ["ar"] = "المستلم" },
        ["nfil.recipient.ph"] = new() { ["en"] = "who it's for", ["es"] = "para quién es", ["fr"] = "à qui c'est destiné", ["de"] = "für wen es ist", ["pt"] = "para quem é", ["it"] = "per chi è", ["ja"] = "誰宛てか", ["zh"] = "发送给谁", ["hi"] = "किसके लिए", ["ar"] = "لمن هو" },
        ["nfil.seal"] = new() { ["en"] = "Seal & create", ["es"] = "Sellar y crear", ["fr"] = "Sceller et créer", ["de"] = "Versiegeln und anlegen", ["pt"] = "Selar e criar", ["it"] = "Sigilla e crea", ["ja"] = "封印して作成", ["zh"] = "封存并创建", ["hi"] = "सील करें और बनाएँ", ["ar"] = "ختم وإنشاء" },
        ["nfil.sub"] = new() { ["en"] = "Seal a file for a recipient under compliance controls. Retention follows the strictest program you pick.", ["es"] = "Sella un archivo para un destinatario bajo controles de cumplimiento. La retención sigue el programa más estricto que elijas.", ["fr"] = "Scellez un fichier pour un destinataire sous contrôles de conformité. La conservation suit le programme le plus strict que vous choisissez.", ["de"] = "Versiegeln Sie eine Datei für einen Empfänger unter Compliance-Kontrollen. Die Aufbewahrung richtet sich nach dem strengsten Programm, das Sie wählen.", ["pt"] = "Sele um ficheiro para um destinatário sob controlos de conformidade. A retenção segue o programa mais estrito que escolher.", ["it"] = "Sigilla un file per un destinatario con controlli di conformità. La conservazione segue il programma più rigoroso che scegli.", ["ja"] = "コンプライアンス管理のもとで受取人向けにファイルを封印します。保持期間は選択した中で最も厳格なプログラムに従います。", ["zh"] = "在合规控制下为接收人封存文件。保留期限遵循你所选最严格的合规方案。", ["hi"] = "अनुपालन नियंत्रणों के तहत प्राप्तकर्ता के लिए फ़ाइल सील करें। प्रतिधारण आपके चुने हुए सबसे कठोर कार्यक्रम का पालन करता है।", ["ar"] = "اختم ملفًا لمستلم وفق ضوابط الامتثال. تتبع مدة الاحتفاظ أشدّ برنامج تختاره." },
        ["nfil.token.hand"] = new() { ["en"] = "Hand this to the recipient out of band; it is the only way to retrieve the file.", ["es"] = "Entrega esto al destinatario por otro canal; es la única forma de recuperar el archivo.", ["fr"] = "Remettez ceci au destinataire par un autre canal ; c'est le seul moyen de récupérer le fichier.", ["de"] = "Übergeben Sie dies dem Empfänger über einen anderen Kanal; es ist der einzige Weg, die Datei abzurufen.", ["pt"] = "Entregue isto ao destinatário por outro canal; é a única forma de recuperar o ficheiro.", ["it"] = "Consegna questo al destinatario per un altro canale; è l'unico modo per recuperare il file.", ["ja"] = "これは別の経路で受取人に渡してください。ファイルを取り出す唯一の手段です。", ["zh"] = "请通过其他渠道将其交给接收人；这是取回该文件的唯一方式。", ["hi"] = "इसे प्राप्तकर्ता को किसी अन्य माध्यम से सौंपें; फ़ाइल पाने का यही एकमात्र रास्ता है।", ["ar"] = "سلّم هذا إلى المستلم عبر قناة أخرى؛ فهو السبيل الوحيد لاسترجاع الملف." },
        ["nfil.token.once"] = new() { ["en"] = "Receive token — shown once", ["es"] = "Token de recepción: se muestra una sola vez", ["fr"] = "Jeton de réception — affiché une seule fois", ["de"] = "Empfangs-Token — nur einmal angezeigt", ["pt"] = "Token de receção — mostrado uma só vez", ["it"] = "Token di ricezione — mostrato una sola volta", ["ja"] = "受信トークン — 一度だけ表示されます", ["zh"] = "接收令牌 — 仅显示一次", ["hi"] = "प्राप्ति टोकन — केवल एक बार दिखाया जाता है", ["ar"] = "رمز الاستلام — يُعرض مرة واحدة" },
        ["nint.content.ph"] = new() { ["en"] = "the file body", ["es"] = "el cuerpo del archivo", ["fr"] = "le corps du fichier", ["de"] = "der Dateiinhalt", ["pt"] = "o corpo do ficheiro", ["it"] = "il corpo del file", ["ja"] = "ファイル本文", ["zh"] = "文件正文", ["hi"] = "फ़ाइल सामग्री", ["ar"] = "محتوى الملف" },
        ["nint.filename.ph"] = new() { ["en"] = "e.g. w2.pdf", ["es"] = "p. ej. w2.pdf", ["fr"] = "ex. w2.pdf", ["de"] = "z. B. w2.pdf", ["pt"] = "p. ex. w2.pdf", ["it"] = "es. w2.pdf", ["ja"] = "例：w2.pdf", ["zh"] = "例如：w2.pdf", ["hi"] = "उदा. w2.pdf", ["ar"] = "مثال: w2.pdf" },
        ["nint.go"] = new() { ["en"] = "Submit into the newest open intake", ["es"] = "Entregar en la recepción abierta más reciente", ["fr"] = "Déposer dans la dernière collecte ouverte", ["de"] = "In die neueste offene Annahme einreichen", ["pt"] = "Entregar na receção aberta mais recente", ["it"] = "Invia all'ultima raccolta aperta", ["ja"] = "最新の受付に提出", ["zh"] = "提交至最新的开放受理", ["hi"] = "नवीनतम खुले इनटेक में जमा करें", ["ar"] = "الإرسال إلى أحدث استلام مفتوح" },
        ["nint.token"] = new() { ["en"] = "Submit token", ["es"] = "Token de entrega", ["fr"] = "Jeton de dépôt", ["de"] = "Einreichungs-Token", ["pt"] = "Token de entrega", ["it"] = "Token di invio", ["ja"] = "提出トークン", ["zh"] = "提交令牌", ["hi"] = "सबमिट टोकन", ["ar"] = "رمز التسليم" },
        ["nint.token.once"] = new() { ["en"] = "Submit token — shown once", ["es"] = "Token de entrega: se muestra una sola vez", ["fr"] = "Jeton de dépôt — affiché une seule fois", ["de"] = "Einreichungs-Token — nur einmal angezeigt", ["pt"] = "Token de entrega — mostrado uma só vez", ["it"] = "Token di invio — mostrato una sola volta", ["ja"] = "提出トークン — 一度だけ表示されます", ["zh"] = "提交令牌 — 仅显示一次", ["hi"] = "सबमिट टोकन — केवल एक बार दिखाया जाता है", ["ar"] = "رمز التسليم — يُعرض مرة واحدة" },
        ["nint.token.ph"] = new() { ["en"] = "intk token", ["es"] = "token intk", ["fr"] = "jeton intk", ["de"] = "intk-Token", ["pt"] = "token intk", ["it"] = "token intk", ["ja"] = "intk トークン", ["zh"] = "intk 令牌", ["hi"] = "intk टोकन", ["ar"] = "رمز intk" },
        ["nint.token.send"] = new() { ["en"] = "Send this to the counterparty out of band; it is their only way in.", ["es"] = "Envía esto a la contraparte por otro canal; es su única vía de entrada.", ["fr"] = "Envoyez ceci à la contrepartie par un autre canal ; c'est sa seule porte d'entrée.", ["de"] = "Senden Sie dies der Gegenpartei über einen anderen Kanal; es ist ihr einziger Zugang.", ["pt"] = "Envie isto à contraparte por outro canal; é a única entrada de que dispõe.", ["it"] = "Invia questo alla controparte per un altro canale; è la sua unica via d'accesso.", ["ja"] = "これは別の経路で相手方に送ってください。相手が入れる唯一の手段です。", ["zh"] = "请通过其他渠道发送给对方；这是对方唯一的进入方式。", ["hi"] = "इसे प्रतिपक्ष को किसी अन्य माध्यम से भेजें; उनके लिए यही एकमात्र प्रवेश है।", ["ar"] = "أرسل هذا إلى الطرف المقابل عبر قناة أخرى؛ فهو مدخله الوحيد." },
        ["nreq.close"] = new() { ["en"] = "Close request", ["es"] = "Cerrar la solicitud", ["fr"] = "Clore la demande", ["de"] = "Anfrage schließen", ["pt"] = "Fechar o pedido", ["it"] = "Chiudi la richiesta", ["ja"] = "依頼を終了する", ["zh"] = "关闭请求", ["hi"] = "अनुरोध बंद करें", ["ar"] = "إغلاق الطلب" },
        ["nreq.from"] = new() { ["en"] = "From", ["es"] = "De", ["fr"] = "De", ["de"] = "Von", ["pt"] = "De", ["it"] = "Da", ["ja"] = "送信元", ["zh"] = "来自", ["hi"] = "से", ["ar"] = "من" },
        ["nreq.from.ph"] = new() { ["en"] = "who should send it", ["es"] = "quién debe enviarlo", ["fr"] = "qui doit l'envoyer", ["de"] = "wer es senden soll", ["pt"] = "quem deve enviá-lo", ["it"] = "chi deve inviarlo", ["ja"] = "誰が送るべきか", ["zh"] = "应由谁发送", ["hi"] = "इसे कौन भेजे", ["ar"] = "من يرسله" },
        ["nreq.go"] = new() { ["en"] = "Request file", ["es"] = "Solicitar archivo", ["fr"] = "Demander le fichier", ["de"] = "Datei anfordern", ["pt"] = "Solicitar ficheiro", ["it"] = "Richiedi il file", ["ja"] = "ファイルを依頼", ["zh"] = "请求文件", ["hi"] = "फ़ाइल का अनुरोध करें", ["ar"] = "طلب ملف" },
        ["nreq.purpose"] = new() { ["en"] = "Purpose (optional)", ["es"] = "Motivo (opcional)", ["fr"] = "Objet (facultatif)", ["de"] = "Zweck (optional)", ["pt"] = "Finalidade (opcional)", ["it"] = "Scopo (facoltativo)", ["ja"] = "目的（任意）", ["zh"] = "用途（可选）", ["hi"] = "उद्देश्य (वैकल्पिक)", ["ar"] = "الغرض (اختياري)" },
        ["nreq.purpose.ph"] = new() { ["en"] = "why you need it", ["es"] = "por qué lo necesitas", ["fr"] = "pourquoi vous en avez besoin", ["de"] = "warum Sie es brauchen", ["pt"] = "porque precisa dele", ["it"] = "perché ti serve", ["ja"] = "なぜ必要か", ["zh"] = "为什么需要它", ["hi"] = "आपको इसकी आवश्यकता क्यों है", ["ar"] = "لماذا تحتاجه" },
        ["ntr.answer.sub"] = new() { ["en"] = "Paste an intake's submit token to answer it — this is what the counterparty does, no vault account involved.", ["es"] = "Pega el token de entrega de una recepción para responderla: esto es lo que hace la contraparte, sin ninguna cuenta de la bóveda.", ["fr"] = "Collez le jeton de dépôt d'une réception pour y répondre — c'est ce que fait la contrepartie, sans aucun compte du coffre.", ["de"] = "Fügen Sie das Einreichungs-Token einer Annahme ein, um sie zu beantworten — das tut die Gegenpartei, ganz ohne Tresorkonto.", ["pt"] = "Cole o token de entrega de uma receção para lhe responder — é o que a contraparte faz, sem qualquer conta do cofre.", ["it"] = "Incolla il token di invio di una ricezione per rispondere — è ciò che fa la controparte, senza alcun account del caveau.", ["ja"] = "受付の提出トークンを貼り付けて応答します — これは相手方が行う操作で、保管庫のアカウントは不要です。", ["zh"] = "粘贴接收的提交令牌以作答复 — 这是对方的操作，无需保险库账户。", ["hi"] = "उत्तर देने के लिए किसी प्राप्ति का सबमिट टोकन चिपकाएँ — यह प्रतिपक्ष करता है, वॉल्ट खाते की आवश्यकता नहीं।", ["ar"] = "الصق رمز تسليم استلامٍ للردّ عليه — هذا ما يفعله الطرف المقابل، دون أي حساب في الخزنة." },
        ["ntr.as.sender"] = new() { ["en"] = "Act as the sender", ["es"] = "Actuar como remitente", ["fr"] = "Agir en tant qu'expéditeur", ["de"] = "Als Absender handeln", ["pt"] = "Agir como remetente", ["it"] = "Agisci come mittente", ["ja"] = "送信者として操作する", ["zh"] = "以发送方身份操作", ["hi"] = "भेजने वाले के रूप में कार्य करें", ["ar"] = "التصرّف بصفة المرسِل" },
        ["ntr.intake"] = new() { ["en"] = "Secure intake", ["es"] = "Recepción segura", ["fr"] = "Réception sécurisée", ["de"] = "Sichere Annahme", ["pt"] = "Receção segura", ["it"] = "Ricezione sicura", ["ja"] = "セキュアな受付", ["zh"] = "安全接收", ["hi"] = "सुरक्षित प्राप्ति", ["ar"] = "استلام آمن" },
        ["ntr.intake.sub"] = new() { ["en"] = "Ask a counterparty to send a file in. They authenticate with the one-shot submit token — no account needed.", ["es"] = "Pide a una contraparte que envíe un archivo. Se autentica con el token de entrega de un solo uso; no necesita cuenta.", ["fr"] = "Demandez à une contrepartie d'envoyer un fichier. Elle s'authentifie avec le jeton de dépôt à usage unique — aucun compte requis.", ["de"] = "Bitten Sie eine Gegenpartei, eine Datei einzusenden. Sie authentifiziert sich mit dem Einmal-Einreichungs-Token — kein Konto nötig.", ["pt"] = "Peça a uma contraparte que envie um ficheiro. Autentica-se com o token de entrega de utilização única — sem necessidade de conta.", ["it"] = "Chiedi a una controparte di inviare un file. Si autentica con il token di invio monouso — nessun account necessario.", ["ja"] = "相手方にファイルの送付を依頼します。相手は使い捨ての提出トークンで認証します — アカウントは不要です。", ["zh"] = "请对方发送文件。对方使用一次性提交令牌进行验证 — 无需账户。", ["hi"] = "किसी प्रतिपक्ष से फ़ाइल भेजने को कहें। वे एक-बार वाले सबमिट टोकन से प्रमाणित होते हैं — किसी खाते की आवश्यकता नहीं।", ["ar"] = "اطلب من الطرف المقابل إرسال ملف. يجري التحقق منه برمز التسليم أحادي الاستخدام — دون حاجة إلى حساب." },
        ["ntr.read"] = new() { ["en"] = "Read sealed file", ["es"] = "Leer el archivo sellado", ["fr"] = "Lire le fichier scellé", ["de"] = "Versiegelte Datei lesen", ["pt"] = "Ler o ficheiro selado", ["it"] = "Leggi il file sigillato", ["ja"] = "封印されたファイルを読む", ["zh"] = "读取封存文件", ["hi"] = "सीलबंद फ़ाइल पढ़ें", ["ar"] = "قراءة الملف المختوم" },
        ["ntr.revoke"] = new() { ["en"] = "Revoke access", ["es"] = "Revocar el acceso", ["fr"] = "Révoquer l'accès", ["de"] = "Zugriff widerrufen", ["pt"] = "Revogar o acesso", ["it"] = "Revoca l'accesso", ["ja"] = "アクセスを取り消す", ["zh"] = "撤销访问权", ["hi"] = "पहुँच निरस्त करें", ["ar"] = "إلغاء الوصول" },
        ["ntr.t.intake"] = new() { ["en"] = "Intake", ["es"] = "Recepción", ["fr"] = "Réception", ["de"] = "Eingang", ["pt"] = "Receção", ["it"] = "In entrata", ["ja"] = "受付", ["zh"] = "接收", ["hi"] = "प्राप्ति", ["ar"] = "استلام" },
        ["ntr.t.outbound"] = new() { ["en"] = "Outbound", ["es"] = "Salientes", ["fr"] = "Sortants", ["de"] = "Ausgehend", ["pt"] = "Enviados", ["it"] = "In uscita", ["ja"] = "送信", ["zh"] = "发出", ["hi"] = "भेजे गए", ["ar"] = "صادر" },
        ["offline.title"] = new() { ["en"] = "What this deployment can reach", ["es"] = "Qué puede alcanzar esta instalación", ["fr"] = "Ce que ce déploiement peut atteindre", ["de"] = "Was diese Installation erreichen kann", ["pt"] = "O que esta instalação pode alcançar", ["it"] = "Cosa può raggiungere questa installazione", ["ja"] = "この環境が接続できる範囲", ["zh"] = "此部署可以连接到什么", ["hi"] = "यह परिनियोजन किस तक पहुँच सकता है", ["ar"] = "ما يمكن أن يصل إليه هذا النشر" },
        ["offline.on"] = new() { ["en"] = "Offline — nothing leaves this machine", ["es"] = "Sin conexión — nada sale de esta máquina", ["fr"] = "Hors ligne — rien ne quitte cette machine", ["de"] = "Offline — nichts verlässt diesen Rechner", ["pt"] = "Offline — nada sai desta máquina", ["it"] = "Offline — nulla esce da questa macchina", ["ja"] = "オフライン — このマシンから何も出ません", ["zh"] = "离线 — 任何内容都不会离开这台机器", ["hi"] = "ऑफ़लाइन — इस मशीन से कुछ भी बाहर नहीं जाता", ["ar"] = "دون اتصال — لا شيء يغادر هذا الجهاز" },
        ["offline.off"] = new() { ["en"] = "Online — this deployment can reach other machines", ["es"] = "En línea — esta instalación puede alcanzar otras máquinas", ["fr"] = "En ligne — ce déploiement peut atteindre d’autres machines", ["de"] = "Online — diese Installation kann andere Rechner erreichen", ["pt"] = "Online — esta instalação pode alcançar outras máquinas", ["it"] = "Online — questa installazione può raggiungere altre macchine", ["ja"] = "オンライン — この環境は他のマシンに接続できます", ["zh"] = "在线 — 此部署可以连接其他机器", ["hi"] = "ऑनलाइन — यह परिनियोजन अन्य मशीनों तक पहुँच सकता है", ["ar"] = "متصل — يمكن لهذا النشر الوصول إلى أجهزة أخرى" },
        ["prb.can"] = new() { ["en"] = "This app can send a count of what failed — the operation and the HTTP status, the day, and how many times. Not what you typed, not who you are, not which profile. Nothing that identifies you or anyone else.", ["es"] = "Esta aplicación puede enviar un recuento de lo que falló: la operación y el estado HTTP, el día y cuántas veces. No lo que escribiste, ni quién eres, ni qué inquilino. Nada que te identifique a ti ni a nadie.", ["fr"] = "Cette application peut envoyer un décompte des échecs : l'opération et le statut HTTP, le jour et le nombre de fois. Pas ce que vous avez saisi, ni qui vous êtes, ni quel locataire. Rien qui vous identifie, ni personne d'autre.", ["de"] = "Diese App kann eine Anzahl der Fehler senden — den Vorgang und den HTTP-Status, den Tag und wie oft. Nicht, was Sie eingegeben haben, nicht, wer Sie sind, nicht welcher Mandant. Nichts, was Sie oder jemand anderen identifiziert.", ["pt"] = "Esta aplicação pode enviar uma contagem do que falhou — a operação e o estado HTTP, o dia e quantas vezes. Não o que escreveu, nem quem é, nem que inquilino. Nada que o identifique a si ou a outra pessoa.", ["it"] = "Questa app può inviare un conteggio degli errori — l'operazione e lo stato HTTP, il giorno e quante volte. Non ciò che hai digitato, non chi sei, non quale tenant. Nulla che identifichi te o chiunque altro.", ["ja"] = "このアプリは失敗の件数を送信できます — 操作と HTTP ステータス、日付、回数です。入力した内容、あなたが誰か、どのテナントかは送りません。あなたや他の誰かを特定するものは何もありません。", ["zh"] = "此应用可以发送失败计数 — 操作与 HTTP 状态、日期以及次数。不包括你输入的内容、你是谁、或哪个租户。没有任何能识别你或他人的信息。", ["hi"] = "यह ऐप विफलताओं की गिनती भेज सकता है — कार्रवाई और HTTP स्थिति, दिन, और कितनी बार। आपने क्या टाइप किया, आप कौन हैं, कौन-सा टेनेंट — कुछ नहीं। ऐसा कुछ भी नहीं जो आपकी या किसी और की पहचान करे।", ["ar"] = "يمكن لهذا التطبيق إرسال عدد ما فشل — العملية وحالة HTTP واليوم وعدد المرات. لا ما كتبته، ولا من أنت، ولا أي مستأجر. لا شيء يعرّفك أو يعرّف أي شخص آخر." },
        ["prb.hide"] = new() { ["en"] = "Hide what would be sent", ["es"] = "Ocultar qué se enviaría", ["fr"] = "Masquer ce qui serait envoyé", ["de"] = "Ausblenden, was gesendet würde", ["pt"] = "Ocultar o que seria enviado", ["it"] = "Nascondi cosa verrebbe inviato", ["ja"] = "送信される内容を隠す", ["zh"] = "隐藏将要发送的内容", ["hi"] = "छिपाएँ क्या भेजा जाएगा", ["ar"] = "إخفاء ما سيُرسَل" },
        ["prb.never"] = new() { ["en"] = "Counts of what failed. Never what you typed.", ["es"] = "Recuentos de lo que falló. Nunca lo que escribiste.", ["fr"] = "Des décomptes d'échecs. Jamais ce que vous avez saisi.", ["de"] = "Anzahl der Fehler. Nie, was Sie eingegeben haben.", ["pt"] = "Contagens do que falhou. Nunca o que escreveu.", ["it"] = "Conteggi degli errori. Mai ciò che hai digitato.", ["ja"] = "失敗した件数だけ。入力した内容は決して送りません。", ["zh"] = "仅统计失败次数。绝不包含你输入的内容。", ["hi"] = "केवल विफलताओं की गिनती। आपने जो लिखा वह कभी नहीं।", ["ar"] = "أعداد ما فشل فقط. أبدًا ما كتبته." },
        ["prb.nowhere"] = new() { ["en"] = "This build reports nowhere. Failures are counted on this machine and never leave it.", ["es"] = "Esta compilación no informa a ninguna parte. Los fallos se cuentan en este equipo y nunca salen de él.", ["fr"] = "Cette version ne signale rien à personne. Les échecs sont comptés sur cette machine et n'en sortent jamais.", ["de"] = "Dieser Build meldet nirgendwohin. Fehler werden auf diesem Gerät gezählt und verlassen es nie.", ["pt"] = "Esta compilação não reporta a lado nenhum. As falhas são contadas nesta máquina e nunca saem dela.", ["it"] = "Questa build non segnala da nessuna parte. Gli errori sono contati su questa macchina e non la lasciano mai.", ["ja"] = "このビルドはどこにも報告しません。障害はこの端末で数えられ、外に出ることはありません。", ["zh"] = "此版本不向任何地方报告。故障只在本机计数，绝不外传。", ["hi"] = "यह बिल्ड कहीं रिपोर्ट नहीं करता। विफलताएँ इसी मशीन पर गिनी जाती हैं और कभी बाहर नहीं जातीं।", ["ar"] = "لا يُبلّغ هذا الإصدار أي جهة. تُحصى الأعطال على هذا الجهاز ولا تغادره أبدًا." },
        ["prb.show"] = new() { ["en"] = "Show what would be sent", ["es"] = "Ver qué se enviaría", ["fr"] = "Voir ce qui serait envoyé", ["de"] = "Anzeigen, was gesendet würde", ["pt"] = "Ver o que seria enviado", ["it"] = "Mostra cosa verrebbe inviato", ["ja"] = "送信される内容を表示", ["zh"] = "查看将要发送的内容", ["hi"] = "देखें क्या भेजा जाएगा", ["ar"] = "إظهار ما سيُرسَل" },
        ["wel.title"] = new() { ["en"] = "Sign in to your vault", ["es"] = "Entra en tu bóveda", ["fr"] = "Connectez-vous à votre coffre", ["de"] = "Melde dich an deinem Tresor an", ["pt"] = "Entre no seu cofre", ["it"] = "Accedi alla tua cassaforte", ["ja"] = "保管庫にサインインする", ["zh"] = "登录你的保险库", ["hi"] = "अपने वॉल्ट में साइन इन करें", ["ar"] = "سجّل الدخول إلى خزنتك" },
        ["wel.sub"] = new() { ["en"] = "Paste the tenant token you were issued. It authorizes every call and never leaves this device unencrypted in transit.", ["es"] = "Pega el token de inquilino que se te entregó. Autoriza cada llamada y nunca sale de este dispositivo sin cifrar.", ["fr"] = "Collez le jeton de locataire qui vous a été remis. Il autorise chaque appel et ne quitte jamais cet appareil en clair.", ["de"] = "Füge das dir ausgestellte Mandanten-Token ein. Es autorisiert jeden Aufruf und verlässt dieses Gerät nie unverschlüsselt.", ["pt"] = "Cole o token de inquilino que lhe foi entregue. Autoriza cada chamada e nunca sai deste dispositivo sem cifra.", ["it"] = "Incolla il token del tenant che ti è stato rilasciato. Autorizza ogni chiamata e non lascia mai questo dispositivo in chiaro.", ["ja"] = "発行されたテナントトークンを貼り付けてください。すべての呼び出しを認可するもので、暗号化されないままこの端末を出ることはありません。", ["zh"] = "粘贴你收到的租户令牌。它为每一次调用授权，并且绝不会以未加密的形式离开这台设备。", ["hi"] = "आपको जारी किया गया टेनेंट टोकन यहाँ चिपकाइए। यह हर कॉल को अधिकृत करता है और बिना कूटलेखन के इस डिवाइस से कभी बाहर नहीं जाता।", ["ar"] = "الصق رمز المستأجر الذي صدر لك. فهو يخوّل كل نداء، ولا يغادر هذا الجهاز غير مُعمّى أبدًا." },
        ["wel.token"] = new() { ["en"] = "Vault token", ["es"] = "Token de la bóveda", ["fr"] = "Jeton du coffre", ["de"] = "Tresor-Token", ["pt"] = "Token do cofre", ["it"] = "Token della cassaforte", ["ja"] = "保管庫のトークン", ["zh"] = "保险库令牌", ["hi"] = "वॉल्ट टोकन", ["ar"] = "رمز الخزنة" },
        ["wel.server"] = new() { ["en"] = "Server", ["es"] = "Servidor", ["fr"] = "Serveur", ["de"] = "Server", ["pt"] = "Servidor", ["it"] = "Server", ["ja"] = "サーバー", ["zh"] = "服务器", ["hi"] = "सर्वर", ["ar"] = "الخادم" },
        ["wel.language"] = new() { ["en"] = "Language", ["es"] = "Idioma", ["fr"] = "Langue", ["de"] = "Sprache", ["pt"] = "Idioma", ["it"] = "Lingua", ["ja"] = "言語", ["zh"] = "语言", ["hi"] = "भाषा", ["ar"] = "اللغة" },
        ["wel.unlock"] = new() { ["en"] = "Unlock", ["es"] = "Desbloquear", ["fr"] = "Déverrouiller", ["de"] = "Entsperren", ["pt"] = "Desbloquear", ["it"] = "Sblocca", ["ja"] = "解錠する", ["zh"] = "解锁", ["hi"] = "खोलें", ["ar"] = "افتح القفل" },
        ["wel.backend"] = new() { ["en"] = "Start the backend:", ["es"] = "Arranca el servidor:", ["fr"] = "Démarrez le serveur :", ["de"] = "Starte das Backend:", ["pt"] = "Inicie o servidor:", ["it"] = "Avvia il backend:", ["ja"] = "バックエンドを起動：", ["zh"] = "启动后端：", ["hi"] = "बैकएंड शुरू कीजिए:", ["ar"] = "شغّل الخادم:" },
        ["action.sign_out"] = new() { ["en"] = "Sign out", ["es"] = "Cerrar sesión", ["fr"] = "Se déconnecter", ["de"] = "Abmelden", ["pt"] = "Sair", ["it"] = "Esci", ["ja"] = "サインアウト", ["zh"] = "退出登录", ["hi"] = "साइन आउट", ["ar"] = "تسجيل الخروج" },
        ["tab.overview"] = new() { ["en"] = "Overview", ["es"] = "Resumen", ["fr"] = "Aperçu", ["de"] = "Übersicht", ["pt"] = "Visão geral", ["it"] = "Panoramica", ["ja"] = "概要", ["zh"] = "概览", ["hi"] = "अवलोकन", ["ar"] = "نظرة عامة" },
        ["tab.vault"] = new() { ["en"] = "Vault", ["es"] = "Bóveda", ["fr"] = "Coffre", ["de"] = "Tresor", ["pt"] = "Cofre", ["it"] = "Cassaforte", ["ja"] = "保管庫", ["zh"] = "保险库", ["hi"] = "वॉल्ट", ["ar"] = "الخزنة" },
        ["tab.audit"] = new() { ["en"] = "Audit", ["es"] = "Auditoría", ["fr"] = "Audit", ["de"] = "Audit", ["pt"] = "Auditoria", ["it"] = "Audit", ["ja"] = "監査", ["zh"] = "审计", ["hi"] = "ऑडिट", ["ar"] = "تدقيق" },
        ["tab.robots"] = new() { ["en"] = "Robots", ["es"] = "Robots", ["fr"] = "Robots", ["de"] = "Roboter", ["pt"] = "Robôs", ["it"] = "Robot", ["ja"] = "ロボット", ["zh"] = "机器人", ["hi"] = "रोबोट", ["ar"] = "روبوتات" },
        ["tab.connectors"] = new() { ["en"] = "Connectors", ["es"] = "Conectores", ["fr"] = "Connecteurs", ["de"] = "Konnektoren", ["pt"] = "Conectores", ["it"] = "Connettori", ["ja"] = "コネクタ", ["zh"] = "连接器", ["hi"] = "कनेक्टर", ["ar"] = "الموصلات" },
        ["tab.transfers"] = new() { ["en"] = "Transfers", ["es"] = "Transferencias", ["fr"] = "Transferts", ["de"] = "Übertragungen", ["pt"] = "Transferências", ["it"] = "Trasferimenti", ["ja"] = "転送", ["zh"] = "传输", ["hi"] = "स्थानांतरण", ["ar"] = "التحويلات" },
        ["action.refresh"] = new() { ["en"] = "Refresh", ["es"] = "Actualizar", ["fr"] = "Actualiser", ["de"] = "Aktualisieren", ["pt"] = "Atualizar", ["it"] = "Aggiorna", ["ja"] = "更新", ["zh"] = "刷新", ["hi"] = "रीफ़्रेश", ["ar"] = "تحديث" },
    };
}
