package com.pdi.vault

import android.content.res.Resources

/**
 * App-chrome localization: tab names and the most common actions, in every
 * language the backend supports. PDI's explanatory notes are localized
 * server-side by the tenant's language setting; this table covers the frame
 * around them. Missing keys fall back to English.
 */
object L10n {
    fun t(key: String, lang: String): String =
        table[key]?.let { it[lang] ?: it["en"] } ?: key

    val supported = listOf("en", "es", "fr", "de", "pt", "it", "ja", "zh",
                           "hi", "ar")

    /**
     * The language of somebody who has no account to take one from.
     *
     * `AppState.language` comes from the stored setting and is "en" until an
     * account exists. Every sentence the backend composes on a public route is
     * chosen from `Accept-Language`, and this shell was sending no such header
     * — the phone has been carrying the answer in the system configuration all
     * along.
     *
     * Region dropped; anything this app does not carry falls back to English
     * rather than guessing.
     */
    fun deviceLanguage(): String {
        val locales = Resources.getSystem().configuration.locales
        for (i in 0 until locales.size()) {
            val base = locales[i].language.lowercase()
            if (supported.contains(base)) return base
        }
        return "en"
    }

    private val table: Map<String, Map<String, String>> = mapOf(
        "ns.acc" to mapOf("en" to "Accessibility", "es" to "Accesibilidad", "fr" to "Accessibilité", "de" to "Barrierefreiheit", "pt" to "Acessibilidade", "it" to "Accessibilità", "ja" to "アクセシビリティ", "zh" to "无障碍", "hi" to "सुलभता", "ar" to "إمكانية الوصول"),
        "ns.acc.lead" to mapOf("en" to "Ability is not a gate. Three questions — no account, no diagnosis, no name. Your words stay on this deployment and become tracked work.", "es" to "La capacidad no es una puerta. Tres preguntas: sin cuenta, sin diagnóstico, sin nombre. Tus palabras se quedan en esta instalación y se convierten en trabajo registrado.", "fr" to "La capacité n’est pas une barrière. Trois questions — pas de compte, pas de diagnostic, pas de nom. Vos mots restent sur cette installation et deviennent du travail suivi.", "de" to "Fähigkeit ist kein Tor. Drei Fragen — kein Konto, keine Diagnose, kein Name. Deine Worte bleiben auf dieser Installation und werden zu verfolgter Arbeit.", "pt" to "Capacidade não é um portão. Três perguntas — sem conta, sem diagnóstico, sem nome. Suas palavras ficam nesta instalação e viram trabalho registrado.", "it" to "L’abilità non è un cancello. Tre domande: niente account, niente diagnosi, niente nome. Le tue parole restano su questa installazione e diventano lavoro tracciato.", "ja" to "能力は門ではありません。質問は3つ — アカウントも診断名も名前も不要です。あなたの言葉はこの環境にとどまり、追跡される作業になります。", "zh" to "能力不是门槛。三个问题——无需账户、无需诊断、无需姓名。你的话留在此部署中，并成为被追踪的工作。", "hi" to "क्षमता कोई द्वार नहीं है। तीन प्रश्न — न खाता, न निदान, न नाम। आपके शब्द इसी परिनियोजन में रहते हैं और दर्ज कार्य बन जाते हैं।", "ar" to "القدرة ليست بوابة. ثلاثة أسئلة — لا حساب ولا تشخيص ولا اسم. تبقى كلماتك على هذا النشر وتصبح عملًا متتبعًا."),
        "ns.acc.needs.title" to mapOf("en" to "Who is expected here", "es" to "A quién esperamos aquí", "fr" to "Qui est attendu ici", "de" to "Wer hier erwartet wird", "pt" to "Quem é esperado aqui", "it" to "Chi è atteso qui", "ja" to "ここに来ることが想定されている人", "zh" to "这里期待谁的到来", "hi" to "यहाँ किनकी अपेक्षा है", "ar" to "من ننتظر هنا"),
        "ns.acc.needs.blind" to mapOf("en" to "Blind and low-vision: every function works by text, images carry descriptions, and the screens use standard controls a screen reader can walk.", "es" to "Personas ciegas o con baja visión: cada función opera por texto, las imágenes llevan descripciones y las pantallas usan controles estándar que un lector de pantalla puede recorrer.", "fr" to "Personnes aveugles ou malvoyantes : chaque fonction passe par le texte, les images portent des descriptions et les écrans utilisent des contrôles standard qu’un lecteur d’écran peut parcourir.", "de" to "Blinde und sehbehinderte Menschen: jede Funktion geht über Text, Bilder tragen Beschreibungen, und die Oberfläche nutzt Standard-Elemente, die ein Screenreader ablaufen kann.", "pt" to "Pessoas cegas ou com baixa visão: toda função opera por texto, as imagens têm descrições e as telas usam controles padrão que um leitor de tela consegue percorrer.", "it" to "Persone cieche o ipovedenti: ogni funzione passa dal testo, le immagini hanno descrizioni e le schermate usano controlli standard che uno screen reader può percorrere.", "ja" to "全盲・弱視の方：すべての機能はテキストで使え、画像には説明が付き、画面はスクリーンリーダーがたどれる標準コントロールでできています。", "zh" to "盲人和低视力者：一切功能都可通过文字完成，图像带有描述，界面使用屏幕阅读器可以遍历的标准控件。", "hi" to "दृष्टिहीन और कम दृष्टि वाले: हर कार्य पाठ से होता है, चित्रों के साथ विवरण है, और स्क्रीन में मानक नियंत्रण हैं जिन्हें स्क्रीन रीडर पढ़ सकता है।", "ar" to "المكفوفون وضعاف البصر: كل وظيفة تعمل بالنص، والصور تحمل أوصافًا، والشاشات تستخدم عناصر قياسية يستطيع قارئ الشاشة تتبعها."),
        "ns.acc.needs.deaf" to mapOf("en" to "Deaf and hard of hearing: nothing here requires sound — voice is always optional, never the only way.", "es" to "Personas sordas o con pérdida auditiva: nada aquí requiere sonido; la voz es siempre opcional, nunca el único camino.", "fr" to "Personnes sourdes ou malentendantes : rien ici n’exige de son — la voix est toujours facultative, jamais le seul chemin.", "de" to "Gehörlose und schwerhörige Menschen: nichts hier verlangt Ton — Sprache ist immer optional, nie der einzige Weg.", "pt" to "Pessoas surdas ou com perda auditiva: nada aqui exige som — a voz é sempre opcional, nunca o único caminho.", "it" to "Persone sorde o con perdita d’udito: niente qui richiede l’audio — la voce è sempre facoltativa, mai l’unica via.", "ja" to "ろう・難聴の方：ここでは音を必要とするものはありません。音声は常に任意で、唯一の手段になることはありません。", "zh" to "聋人和听障者：这里没有任何功能依赖声音——语音永远是可选的，绝不是唯一途径。", "hi" to "बधिर और कम सुनने वाले: यहाँ किसी चीज़ के लिए ध्वनि आवश्यक नहीं — आवाज़ हमेशा वैकल्पिक है, कभी एकमात्र रास्ता नहीं।", "ar" to "الصم وضعاف السمع: لا شيء هنا يتطلب صوتًا — الصوت اختياري دائمًا، وليس الطريق الوحيد أبدًا."),
        "ns.acc.needs.mute" to mapOf("en" to "Mute and nonspeaking: nothing here requires speaking — anywhere a microphone is offered, typing does the same job.", "es" to "Personas mudas o que no hablan: nada aquí requiere hablar; donde se ofrece un micrófono, escribir hace el mismo trabajo.", "fr" to "Personnes muettes ou non verbales : rien ici n’exige de parler — partout où un micro est proposé, écrire fait le même travail.", "de" to "Stumme und nicht sprechende Menschen: nichts hier verlangt Sprechen — überall, wo ein Mikrofon angeboten wird, tut Tippen denselben Dienst.", "pt" to "Pessoas mudas ou não falantes: nada aqui exige falar — onde houver microfone, digitar faz o mesmo trabalho.", "it" to "Persone mute o non parlanti: niente qui richiede di parlare — ovunque ci sia un microfono, scrivere fa lo stesso lavoro.", "ja" to "発話しない方・発話が難しい方：ここでは話すことを必要とするものはありません。マイクがある場所ではどこでも、入力が同じ役割を果たします。", "zh" to "失语和不说话的人：这里没有任何功能要求开口——凡是提供麦克风的地方，打字都能完成同样的事。", "hi" to "मूक और न बोलने वाले: यहाँ बोलना आवश्यक नहीं — जहाँ भी माइक्रोफ़ोन है, वहाँ टाइप करना वही काम करता है।", "ar" to "البُكم ومن لا يتكلمون: لا شيء هنا يتطلب الكلام — أينما وُجد ميكروفون، تقوم الكتابة بالمهمة نفسها."),
        "ns.acc.needs.motor" to mapOf("en" to "Limited mobility, amputation, tremor: every control is a standard element the keyboard alone can reach, and no step in this console is timed.", "es" to "Movilidad reducida, amputación, temblor: cada control es un elemento estándar alcanzable solo con el teclado, y ningún paso de esta consola tiene límite de tiempo.", "fr" to "Mobilité réduite, amputation, tremblement : chaque contrôle est un élément standard atteignable au clavier seul, et aucune étape de cette console n’est chronométrée.", "de" to "Eingeschränkte Mobilität, Amputation, Tremor: jedes Element ist ein Standard-Element, das die Tastatur allein erreicht, und kein Schritt in dieser Konsole hat ein Zeitlimit.", "pt" to "Mobilidade reduzida, amputação, tremor: todo controle é um elemento padrão alcançável só pelo teclado, e nenhum passo neste console é cronometrado.", "it" to "Mobilità ridotta, amputazione, tremore: ogni controllo è un elemento standard raggiungibile con la sola tastiera, e nessun passaggio in questa console è a tempo.", "ja" to "運動機能の制約・切断・振戦のある方：すべてのコントロールはキーボードだけで届く標準要素で、このコンソールに制限時間のある操作はありません。", "zh" to "行动不便、截肢、震颤者：每个控件都是仅用键盘即可到达的标准元素，本控制台没有任何限时步骤。", "hi" to "सीमित गतिशीलता, अंग-विच्छेद, कंपन: हर नियंत्रण एक मानक तत्व है जिस तक केवल कीबोर्ड से पहुँचा जा सकता है, और इस कंसोल में कोई चरण समयबद्ध नहीं है।", "ar" to "محدودية الحركة والبتر والرُعاش: كل عنصر تحكم قياسي تصل إليه لوحة المفاتيح وحدها، ولا خطوة في هذه الواجهة مقيدة بوقت."),
        "ns.acc.needs.cognitive" to mapOf("en" to "Autistic and cognitively different people: plain words, one step at a time, nothing flashes, and asking again is always free.", "es" to "Personas autistas y cognitivamente diversas: palabras llanas, un paso a la vez, nada parpadea, y volver a preguntar es siempre gratis.", "fr" to "Personnes autistes et cognitivement différentes : des mots simples, une étape à la fois, rien ne clignote, et redemander est toujours gratuit.", "de" to "Autistische und kognitiv verschiedene Menschen: einfache Worte, ein Schritt nach dem anderen, nichts blinkt, und noch einmal fragen kostet nie etwas.", "pt" to "Pessoas autistas e cognitivamente diversas: palavras simples, um passo de cada vez, nada pisca, e perguntar de novo é sempre grátis.", "it" to "Persone autistiche e cognitivamente diverse: parole semplici, un passo alla volta, niente lampeggia, e chiedere di nuovo non costa mai nulla.", "ja" to "自閉スペクトラムの方・認知の仕方が異なる方：平易な言葉、一度にひとつの手順、点滅するものはなく、もう一度尋ねることはいつでも自由です。", "zh" to "自闭症和认知方式不同的人：语言平实，一次一步，没有闪烁的内容，再问一遍永远无妨。", "hi" to "ऑटिस्टिक और संज्ञानात्मक रूप से भिन्न लोग: सरल शब्द, एक समय में एक कदम, कुछ नहीं चमकता, और दोबारा पूछना हमेशा निःशुल्क है।", "ar" to "المصابون بالتوحد والمختلفون إدراكيًا: كلمات بسيطة، خطوة واحدة في كل مرة، لا شيء يومض، والسؤال مرة أخرى مجاني دائمًا."),
        "ns.acc.needs.dyslexia" to mapOf("en" to "Dyslexia and reading differences: short sentences, real headings, and nothing that punishes rereading.", "es" to "Dislexia y diferencias de lectura: frases cortas, encabezados reales y nada que castigue releer.", "fr" to "Dyslexie et différences de lecture : phrases courtes, vrais titres, et rien qui punisse la relecture.", "de" to "Dyslexie und Leseunterschiede: kurze Sätze, echte Überschriften, und nichts bestraft erneutes Lesen.", "pt" to "Dislexia e diferenças de leitura: frases curtas, títulos de verdade e nada que puna reler.", "it" to "Dislessia e differenze di lettura: frasi brevi, titoli veri e niente che punisca il rileggere.", "ja" to "ディスレクシア・読み方の異なる方：短い文、本物の見出し、読み返しても不利にならない画面。", "zh" to "阅读障碍者：短句、真实的标题，重读不会受到任何惩罚。", "hi" to "डिस्लेक्सिया और पढ़ने की भिन्नताएँ: छोटे वाक्य, वास्तविक शीर्षक, और दोबारा पढ़ने पर कोई दंड नहीं।", "ar" to "عسر القراءة وفروق القراءة: جمل قصيرة وعناوين حقيقية ولا شيء يعاقب على إعادة القراءة."),
        "ns.acc.needs.motion" to mapOf("en" to "Motion sensitivity: when your device asks for reduced motion, this console stops animating.", "es" to "Sensibilidad al movimiento: cuando tu dispositivo pide movimiento reducido, esta consola deja de animar.", "fr" to "Sensibilité au mouvement : quand votre appareil demande une animation réduite, cette console cesse d’animer.", "de" to "Bewegungsempfindlichkeit: wenn dein Gerät reduzierte Bewegung verlangt, hört diese Konsole auf zu animieren.", "pt" to "Sensibilidade a movimento: quando seu dispositivo pede movimento reduzido, este console para de animar.", "it" to "Sensibilità al movimento: quando il tuo dispositivo chiede movimento ridotto, questa console smette di animare.", "ja" to "動きに敏感な方：端末が「視差効果を減らす」を求めると、このコンソールはアニメーションを止めます。", "zh" to "对动态敏感者：当你的设备要求减少动态效果时，本控制台会停止动画。", "hi" to "गति के प्रति संवेदनशीलता: जब आपका उपकरण कम गति माँगता है, यह कंसोल एनिमेशन बंद कर देता है।", "ar" to "الحساسية للحركة: عندما يطلب جهازك تقليل الحركة، تتوقف هذه الواجهة عن التحريك."),
        "ns.acc.needs.more" to mapOf("en" to "Not on this list? The gap is in the list, not in you. Name it below and it becomes our work.", "es" to "¿No estás en esta lista? El vacío está en la lista, no en ti. Nómbralo abajo y se convierte en nuestro trabajo.", "fr" to "Pas sur cette liste ? Le manque est dans la liste, pas en vous. Nommez-le ci-dessous et cela devient notre travail.", "de" to "Nicht auf dieser Liste? Die Lücke ist in der Liste, nicht in dir. Benenne sie unten, und sie wird unsere Arbeit.", "pt" to "Não está nesta lista? A lacuna está na lista, não em você. Nomeie-a abaixo e ela vira nosso trabalho.", "it" to "Non sei in questa lista? La lacuna è nella lista, non in te. Nominala qui sotto e diventa il nostro lavoro.", "ja" to "この一覧にありませんか？足りないのは一覧であって、あなたではありません。下で名前を付けてください。それが私たちの仕事になります。", "zh" to "不在这份清单上？缺的是清单，不是你。在下方写出来，它就成为我们的工作。", "hi" to "इस सूची में नहीं हैं? कमी सूची में है, आप में नहीं। नीचे उसे नाम दें और वह हमारा काम बन जाएगा।", "ar" to "لست في هذه القائمة؟ النقص في القائمة لا فيك. اذكره أدناه وسيصبح عملنا."),
        "ns.acc.doing.ph" to mapOf("en" to "What were you trying to do?", "es" to "¿Qué intentabas hacer?", "fr" to "Qu’essayiez-vous de faire ?", "de" to "Was hast du versucht zu tun?", "pt" to "O que você estava tentando fazer?", "it" to "Cosa stavi cercando di fare?", "ja" to "何をしようとしていましたか？", "zh" to "你当时想做什么？", "hi" to "आप क्या करने की कोशिश कर रहे थे?", "ar" to "ما الذي كنت تحاول فعله؟"),
        "ns.acc.wall.ph" to mapOf("en" to "What stood in the way?", "es" to "¿Qué se interpuso?", "fr" to "Qu’est-ce qui a fait obstacle ?", "de" to "Was stand im Weg?", "pt" to "O que ficou no caminho?", "it" to "Cosa ti ha ostacolato?", "ja" to "何が妨げになりましたか？", "zh" to "是什么挡住了你？", "hi" to "क्या आड़े आया?", "ar" to "ما الذي وقف في الطريق؟"),
        "ns.acc.help.ph" to mapOf("en" to "What would help? (optional)", "es" to "¿Qué ayudaría? (opcional)", "fr" to "Qu’est-ce qui aiderait ? (facultatif)", "de" to "Was würde helfen? (optional)", "pt" to "O que ajudaria? (opcional)", "it" to "Cosa aiuterebbe? (facoltativo)", "ja" to "何があれば助かりますか？（任意）", "zh" to "什么会有帮助？（可选）", "hi" to "क्या मदद करेगा? (वैकल्पिक)", "ar" to "ما الذي قد يساعد؟ (اختياري)"),
        "ns.acc.send" to mapOf("en" to "Send report", "es" to "Enviar informe", "fr" to "Envoyer le signalement", "de" to "Bericht senden", "pt" to "Enviar relato", "it" to "Invia la segnalazione", "ja" to "報告を送る", "zh" to "发送报告", "hi" to "रिपोर्ट भेजें", "ar" to "أرسل البلاغ"),
        "ns.acc.sent" to mapOf("en" to "Received — thank you.", "es" to "Recibido. Gracias.", "fr" to "Reçu — merci.", "de" to "Angekommen — danke.", "pt" to "Recebido — obrigado.", "it" to "Ricevuto — grazie.", "ja" to "受け取りました。ありがとうございます。", "zh" to "已收到——谢谢。", "hi" to "प्राप्त हुआ — धन्यवाद।", "ar" to "وصل البلاغ — شكرًا لك."),
        "ns.acc.token.ph" to mapOf("en" to "Reviewer token", "es" to "Token de revisor", "fr" to "Jeton de réviseur", "de" to "Prüfer-Token", "pt" to "Token de revisor", "it" to "Token del revisore", "ja" to "レビュアートークン", "zh" to "审阅者令牌", "hi" to "समीक्षक टोकन", "ar" to "رمز المراجع"),
        "ns.acc.load" to mapOf("en" to "Load reports", "es" to "Cargar informes", "fr" to "Charger les signalements", "de" to "Berichte laden", "pt" to "Carregar relatos", "it" to "Carica le segnalazioni", "ja" to "報告を読み込む", "zh" to "载入报告", "hi" to "रिपोर्टें लोड करें", "ar" to "حمّل البلاغات"),
        "ns.acc.none" to mapOf("en" to "No reports yet.", "es" to "Aún no hay informes.", "fr" to "Aucun signalement pour l’instant.", "de" to "Noch keine Berichte.", "pt" to "Ainda não há relatos.", "it" to "Ancora nessuna segnalazione.", "ja" to "まだ報告はありません。", "zh" to "还没有报告。", "hi" to "अभी कोई रिपोर्ट नहीं।", "ar" to "لا بلاغات بعد."),
        "nacc.handle" to mapOf("en" to "Handle (optional)", "es" to "Identificador (opcional)", "fr" to "Identifiant (facultatif)", "de" to "Kennung (optional)", "pt" to "Identificador (opcional)", "it" to "Handle (facoltativo)", "ja" to "ハンドル（任意）", "zh" to "用户名（可选）", "hi" to "हैंडल (वैकल्पिक)", "ar" to "المعرّف (اختياري)"),
        "nacc.handle.ph" to mapOf("en" to "@account", "es" to "@cuenta", "fr" to "@compte", "de" to "@konto", "pt" to "@conta", "it" to "@account", "ja" to "@アカウント", "zh" to "@账户", "hi" to "@खाता", "ar" to "@حساب"),
        "nacc.id.ph" to mapOf("en" to "pdi_…", "es" to "pdi_…", "fr" to "pdi_…", "de" to "pdi_…", "pt" to "pdi_…", "it" to "pdi_…", "ja" to "pdi_…", "zh" to "pdi_…", "hi" to "pdi_…", "ar" to "pdi_…"),
        "nadm.retire" to mapOf("en" to "Retire old", "es" to "Retirar la anterior", "fr" to "Retirer l'ancienne", "de" to "Alte zurückziehen", "pt" to "Retirar a anterior", "it" to "Ritira la vecchia", "ja" to "旧鍵を廃止", "zh" to "停用旧密钥", "hi" to "पुरानी हटाएँ", "ar" to "سحب القديم"),
        "nadm.rotate" to mapOf("en" to "Rotate key", "es" to "Rotar la clave", "fr" to "Faire tourner la clé", "de" to "Schlüssel rotieren", "pt" to "Rodar a chave", "it" to "Ruota la chiave", "ja" to "鍵をローテーション", "zh" to "轮换密钥", "hi" to "कुंजी घुमाएँ", "ar" to "تدوير المفتاح"),
        "nadm.token" to mapOf("en" to "Admin token", "es" to "Token de administrador", "fr" to "Jeton d'administration", "de" to "Admin-Token", "pt" to "Token de administrador", "it" to "Token di amministrazione", "ja" to "管理者トークン", "zh" to "管理员令牌", "hi" to "एडमिन टोकन", "ar" to "رمز المشرف"),
        "nadm.versions" to mapOf("en" to "Load versions", "es" to "Cargar versiones", "fr" to "Charger les versions", "de" to "Versionen laden", "pt" to "Carregar versões", "it" to "Carica le versioni", "ja" to "バージョンを読み込む", "zh" to "加载版本", "hi" to "संस्करण लोड करें", "ar" to "تحميل الإصدارات"),
        "nfb.msg.ph" to mapOf("en" to "What's on your mind?", "es" to "¿Qué te preocupa?", "fr" to "Qu'avez-vous en tête ?", "de" to "Was beschäftigt Sie?", "pt" to "O que lhe vai na cabeça?", "it" to "A cosa stai pensando?", "ja" to "気になっていることは？", "zh" to "你在想什么？", "hi" to "आपके मन में क्या है?", "ar" to "بماذا تفكر؟"),
        "nfb.send" to mapOf("en" to "Send feedback", "es" to "Enviar comentarios", "fr" to "Envoyer un retour", "de" to "Rückmeldung senden", "pt" to "Enviar comentários", "it" to "Invia un riscontro", "ja" to "フィードバックを送る", "zh" to "发送反馈", "hi" to "प्रतिक्रिया भेजें", "ar" to "إرسال ملاحظات"),
        "nfil.content" to mapOf("en" to "Content", "es" to "Contenido", "fr" to "Contenu", "de" to "Inhalt", "pt" to "Conteúdo", "it" to "Contenuto", "ja" to "内容", "zh" to "内容", "hi" to "सामग्री", "ar" to "المحتوى"),
        "nfil.content.ph" to mapOf("en" to "the file body to seal", "es" to "el cuerpo del archivo a sellar", "fr" to "le corps du fichier à sceller", "de" to "der zu versiegelnde Dateiinhalt", "pt" to "o corpo do ficheiro a selar", "it" to "il corpo del file da sigillare", "ja" to "封印するファイル本文", "zh" to "要封存的文件正文", "hi" to "सील करने हेतु फ़ाइल सामग्री", "ar" to "محتوى الملف المراد ختمه"),
        "nfil.filename" to mapOf("en" to "Filename", "es" to "Nombre de archivo", "fr" to "Nom du fichier", "de" to "Dateiname", "pt" to "Nome do ficheiro", "it" to "Nome del file", "ja" to "ファイル名", "zh" to "文件名", "hi" to "फ़ाइल नाम", "ar" to "اسم الملف"),
        "nfil.filename.ph" to mapOf("en" to "e.g. results.pdf", "es" to "p. ej. resultados.pdf", "fr" to "ex. resultats.pdf", "de" to "z. B. ergebnisse.pdf", "pt" to "p. ex. resultados.pdf", "it" to "es. risultati.pdf", "ja" to "例：results.pdf", "zh" to "例如：results.pdf", "hi" to "उदा. results.pdf", "ar" to "مثال: results.pdf"),
        "nfil.programs" to mapOf("en" to "Programs", "es" to "Programas", "fr" to "Programmes", "de" to "Programme", "pt" to "Programas", "it" to "Programmi", "ja" to "プログラム", "zh" to "合规方案", "hi" to "कार्यक्रम", "ar" to "البرامج"),
        "nfil.recipient" to mapOf("en" to "Recipient", "es" to "Destinatario", "fr" to "Destinataire", "de" to "Empfänger", "pt" to "Destinatário", "it" to "Destinatario", "ja" to "受取人", "zh" to "接收人", "hi" to "प्राप्तकर्ता", "ar" to "المستلم"),
        "nfil.recipient.ph" to mapOf("en" to "who it's for", "es" to "para quién es", "fr" to "à qui c'est destiné", "de" to "für wen es ist", "pt" to "para quem é", "it" to "per chi è", "ja" to "誰宛てか", "zh" to "发送给谁", "hi" to "किसके लिए", "ar" to "لمن هو"),
        "nfil.seal" to mapOf("en" to "Seal & create", "es" to "Sellar y crear", "fr" to "Sceller et créer", "de" to "Versiegeln und anlegen", "pt" to "Selar e criar", "it" to "Sigilla e crea", "ja" to "封印して作成", "zh" to "封存并创建", "hi" to "सील करें और बनाएँ", "ar" to "ختم وإنشاء"),
        "nfil.sub" to mapOf("en" to "Seal a file for a recipient under compliance controls. Retention follows the strictest program you pick.", "es" to "Sella un archivo para un destinatario bajo controles de cumplimiento. La retención sigue el programa más estricto que elijas.", "fr" to "Scellez un fichier pour un destinataire sous contrôles de conformité. La conservation suit le programme le plus strict que vous choisissez.", "de" to "Versiegeln Sie eine Datei für einen Empfänger unter Compliance-Kontrollen. Die Aufbewahrung richtet sich nach dem strengsten Programm, das Sie wählen.", "pt" to "Sele um ficheiro para um destinatário sob controlos de conformidade. A retenção segue o programa mais estrito que escolher.", "it" to "Sigilla un file per un destinatario con controlli di conformità. La conservazione segue il programma più rigoroso che scegli.", "ja" to "コンプライアンス管理のもとで受取人向けにファイルを封印します。保持期間は選択した中で最も厳格なプログラムに従います。", "zh" to "在合规控制下为接收人封存文件。保留期限遵循你所选最严格的合规方案。", "hi" to "अनुपालन नियंत्रणों के तहत प्राप्तकर्ता के लिए फ़ाइल सील करें। प्रतिधारण आपके चुने हुए सबसे कठोर कार्यक्रम का पालन करता है।", "ar" to "اختم ملفًا لمستلم وفق ضوابط الامتثال. تتبع مدة الاحتفاظ أشدّ برنامج تختاره."),
        "nfil.token.hand" to mapOf("en" to "Hand this to the recipient out of band; it is the only way to retrieve the file.", "es" to "Entrega esto al destinatario por otro canal; es la única forma de recuperar el archivo.", "fr" to "Remettez ceci au destinataire par un autre canal ; c'est le seul moyen de récupérer le fichier.", "de" to "Übergeben Sie dies dem Empfänger über einen anderen Kanal; es ist der einzige Weg, die Datei abzurufen.", "pt" to "Entregue isto ao destinatário por outro canal; é a única forma de recuperar o ficheiro.", "it" to "Consegna questo al destinatario per un altro canale; è l'unico modo per recuperare il file.", "ja" to "これは別の経路で受取人に渡してください。ファイルを取り出す唯一の手段です。", "zh" to "请通过其他渠道将其交给接收人；这是取回该文件的唯一方式。", "hi" to "इसे प्राप्तकर्ता को किसी अन्य माध्यम से सौंपें; फ़ाइल पाने का यही एकमात्र रास्ता है।", "ar" to "سلّم هذا إلى المستلم عبر قناة أخرى؛ فهو السبيل الوحيد لاسترجاع الملف."),
        "nfil.token.once" to mapOf("en" to "Receive token — shown once", "es" to "Token de recepción: se muestra una sola vez", "fr" to "Jeton de réception — affiché une seule fois", "de" to "Empfangs-Token — nur einmal angezeigt", "pt" to "Token de receção — mostrado uma só vez", "it" to "Token di ricezione — mostrato una sola volta", "ja" to "受信トークン — 一度だけ表示されます", "zh" to "接收令牌 — 仅显示一次", "hi" to "प्राप्ति टोकन — केवल एक बार दिखाया जाता है", "ar" to "رمز الاستلام — يُعرض مرة واحدة"),
        "nint.content.ph" to mapOf("en" to "the file body", "es" to "el cuerpo del archivo", "fr" to "le corps du fichier", "de" to "der Dateiinhalt", "pt" to "o corpo do ficheiro", "it" to "il corpo del file", "ja" to "ファイル本文", "zh" to "文件正文", "hi" to "फ़ाइल सामग्री", "ar" to "محتوى الملف"),
        "nint.filename.ph" to mapOf("en" to "e.g. w2.pdf", "es" to "p. ej. w2.pdf", "fr" to "ex. w2.pdf", "de" to "z. B. w2.pdf", "pt" to "p. ex. w2.pdf", "it" to "es. w2.pdf", "ja" to "例：w2.pdf", "zh" to "例如：w2.pdf", "hi" to "उदा. w2.pdf", "ar" to "مثال: w2.pdf"),
        "nint.go" to mapOf("en" to "Submit into the newest open intake", "es" to "Entregar en la recepción abierta más reciente", "fr" to "Déposer dans la dernière collecte ouverte", "de" to "In die neueste offene Annahme einreichen", "pt" to "Entregar na receção aberta mais recente", "it" to "Invia all'ultima raccolta aperta", "ja" to "最新の受付に提出", "zh" to "提交至最新的开放受理", "hi" to "नवीनतम खुले इनटेक में जमा करें", "ar" to "الإرسال إلى أحدث استلام مفتوح"),
        "nint.token" to mapOf("en" to "Submit token", "es" to "Token de entrega", "fr" to "Jeton de dépôt", "de" to "Einreichungs-Token", "pt" to "Token de entrega", "it" to "Token di invio", "ja" to "提出トークン", "zh" to "提交令牌", "hi" to "सबमिट टोकन", "ar" to "رمز التسليم"),
        "nint.token.once" to mapOf("en" to "Submit token — shown once", "es" to "Token de entrega: se muestra una sola vez", "fr" to "Jeton de dépôt — affiché une seule fois", "de" to "Einreichungs-Token — nur einmal angezeigt", "pt" to "Token de entrega — mostrado uma só vez", "it" to "Token di invio — mostrato una sola volta", "ja" to "提出トークン — 一度だけ表示されます", "zh" to "提交令牌 — 仅显示一次", "hi" to "सबमिट टोकन — केवल एक बार दिखाया जाता है", "ar" to "رمز التسليم — يُعرض مرة واحدة"),
        "nint.token.ph" to mapOf("en" to "intk token", "es" to "token intk", "fr" to "jeton intk", "de" to "intk-Token", "pt" to "token intk", "it" to "token intk", "ja" to "intk トークン", "zh" to "intk 令牌", "hi" to "intk टोकन", "ar" to "رمز intk"),
        "nint.token.send" to mapOf("en" to "Send this to the counterparty out of band; it is their only way in.", "es" to "Envía esto a la contraparte por otro canal; es su única vía de entrada.", "fr" to "Envoyez ceci à la contrepartie par un autre canal ; c'est sa seule porte d'entrée.", "de" to "Senden Sie dies der Gegenpartei über einen anderen Kanal; es ist ihr einziger Zugang.", "pt" to "Envie isto à contraparte por outro canal; é a única entrada de que dispõe.", "it" to "Invia questo alla controparte per un altro canale; è la sua unica via d'accesso.", "ja" to "これは別の経路で相手方に送ってください。相手が入れる唯一の手段です。", "zh" to "请通过其他渠道发送给对方；这是对方唯一的进入方式。", "hi" to "इसे प्रतिपक्ष को किसी अन्य माध्यम से भेजें; उनके लिए यही एकमात्र प्रवेश है।", "ar" to "أرسل هذا إلى الطرف المقابل عبر قناة أخرى؛ فهو مدخله الوحيد."),
        "nrec.key" to mapOf("en" to "Key", "es" to "Clave", "fr" to "Clé", "de" to "Schlüssel", "pt" to "Chave", "it" to "Chiave", "ja" to "キー", "zh" to "键名", "hi" to "कुंजी", "ar" to "المفتاح"),
        "nrec.key.ph" to mapOf("en" to "e.g. ssn", "es" to "p. ej. ssn", "fr" to "ex. ssn", "de" to "z. B. ssn", "pt" to "p. ex. ssn", "it" to "es. ssn", "ja" to "例：ssn", "zh" to "例如：ssn", "hi" to "उदा. ssn", "ar" to "مثال: ssn"),
        "nrec.seal" to mapOf("en" to "Seal record", "es" to "Sellar el registro", "fr" to "Sceller l'enregistrement", "de" to "Datensatz versiegeln", "pt" to "Selar o registo", "it" to "Sigilla il record", "ja" to "レコードを封印", "zh" to "封存记录", "hi" to "रिकॉर्ड सील करें", "ar" to "ختم السجل"),
        "nrec.t.records" to mapOf("en" to "Records", "es" to "Registros", "fr" to "Enregistrements", "de" to "Datensätze", "pt" to "Registos", "it" to "Record", "ja" to "レコード", "zh" to "记录", "hi" to "रिकॉर्ड", "ar" to "السجلات"),
        "nrec.value" to mapOf("en" to "Value", "es" to "Valor", "fr" to "Valeur", "de" to "Wert", "pt" to "Valor", "it" to "Valore", "ja" to "値", "zh" to "值", "hi" to "मान", "ar" to "القيمة"),
        "nrec.value.ph" to mapOf("en" to "plaintext to seal", "es" to "texto a sellar", "fr" to "texte en clair à sceller", "de" to "zu versiegelnder Klartext", "pt" to "texto a selar", "it" to "testo in chiaro da sigillare", "ja" to "封印する平文", "zh" to "要封存的明文", "hi" to "सील करने हेतु सादा पाठ", "ar" to "نص للختم"),
        "nreq.close" to mapOf("en" to "Close request", "es" to "Cerrar la solicitud", "fr" to "Clore la demande", "de" to "Anfrage schließen", "pt" to "Fechar o pedido", "it" to "Chiudi la richiesta", "ja" to "依頼を終了する", "zh" to "关闭请求", "hi" to "अनुरोध बंद करें", "ar" to "إغلاق الطلب"),
        "nreq.from" to mapOf("en" to "From", "es" to "De", "fr" to "De", "de" to "Von", "pt" to "De", "it" to "Da", "ja" to "送信元", "zh" to "来自", "hi" to "से", "ar" to "من"),
        "nreq.from.ph" to mapOf("en" to "who should send it", "es" to "quién debe enviarlo", "fr" to "qui doit l'envoyer", "de" to "wer es senden soll", "pt" to "quem deve enviá-lo", "it" to "chi deve inviarlo", "ja" to "誰が送るべきか", "zh" to "应由谁发送", "hi" to "इसे कौन भेजे", "ar" to "من يرسله"),
        "nreq.go" to mapOf("en" to "Request file", "es" to "Solicitar archivo", "fr" to "Demander le fichier", "de" to "Datei anfordern", "pt" to "Solicitar ficheiro", "it" to "Richiedi il file", "ja" to "ファイルを依頼", "zh" to "请求文件", "hi" to "फ़ाइल का अनुरोध करें", "ar" to "طلب ملف"),
        "nreq.purpose" to mapOf("en" to "Purpose (optional)", "es" to "Motivo (opcional)", "fr" to "Objet (facultatif)", "de" to "Zweck (optional)", "pt" to "Finalidade (opcional)", "it" to "Scopo (facoltativo)", "ja" to "目的（任意）", "zh" to "用途（可选）", "hi" to "उद्देश्य (वैकल्पिक)", "ar" to "الغرض (اختياري)"),
        "nreq.purpose.ph" to mapOf("en" to "why you need it", "es" to "por qué lo necesitas", "fr" to "pourquoi vous en avez besoin", "de" to "warum Sie es brauchen", "pt" to "porque precisa dele", "it" to "perché ti serve", "ja" to "なぜ必要か", "zh" to "为什么需要它", "hi" to "आपको इसकी आवश्यकता क्यों है", "ar" to "لماذا تحتاجه"),
        "nrob.bind.go" to mapOf("en" to "Bind", "es" to "Vincular", "fr" to "Associer", "de" to "Verbinden", "pt" to "Vincular", "it" to "Collega", "ja" to "接続", "zh" to "绑定", "hi" to "जोड़ें", "ar" to "ربط"),
        "ntr.answer.sub" to mapOf("en" to "Paste an intake's submit token to answer it — this is what the counterparty does, no vault account involved.", "es" to "Pega el token de entrega de una recepción para responderla: esto es lo que hace la contraparte, sin ninguna cuenta de la bóveda.", "fr" to "Collez le jeton de dépôt d'une réception pour y répondre — c'est ce que fait la contrepartie, sans aucun compte du coffre.", "de" to "Fügen Sie das Einreichungs-Token einer Annahme ein, um sie zu beantworten — das tut die Gegenpartei, ganz ohne Tresorkonto.", "pt" to "Cole o token de entrega de uma receção para lhe responder — é o que a contraparte faz, sem qualquer conta do cofre.", "it" to "Incolla il token di invio di una ricezione per rispondere — è ciò che fa la controparte, senza alcun account del caveau.", "ja" to "受付の提出トークンを貼り付けて応答します — これは相手方が行う操作で、保管庫のアカウントは不要です。", "zh" to "粘贴接收的提交令牌以作答复 — 这是对方的操作，无需保险库账户。", "hi" to "उत्तर देने के लिए किसी प्राप्ति का सबमिट टोकन चिपकाएँ — यह प्रतिपक्ष करता है, वॉल्ट खाते की आवश्यकता नहीं।", "ar" to "الصق رمز تسليم استلامٍ للردّ عليه — هذا ما يفعله الطرف المقابل، دون أي حساب في الخزنة."),
        "ntr.as.sender" to mapOf("en" to "Act as the sender", "es" to "Actuar como remitente", "fr" to "Agir en tant qu'expéditeur", "de" to "Als Absender handeln", "pt" to "Agir como remetente", "it" to "Agisci come mittente", "ja" to "送信者として操作する", "zh" to "以发送方身份操作", "hi" to "भेजने वाले के रूप में कार्य करें", "ar" to "التصرّف بصفة المرسِل"),
        "ntr.intake" to mapOf("en" to "Secure intake", "es" to "Recepción segura", "fr" to "Réception sécurisée", "de" to "Sichere Annahme", "pt" to "Receção segura", "it" to "Ricezione sicura", "ja" to "セキュアな受付", "zh" to "安全接收", "hi" to "सुरक्षित प्राप्ति", "ar" to "استلام آمن"),
        "ntr.intake.sub" to mapOf("en" to "Ask a counterparty to send a file in. They authenticate with the one-shot submit token — no account needed.", "es" to "Pide a una contraparte que envíe un archivo. Se autentica con el token de entrega de un solo uso; no necesita cuenta.", "fr" to "Demandez à une contrepartie d'envoyer un fichier. Elle s'authentifie avec le jeton de dépôt à usage unique — aucun compte requis.", "de" to "Bitten Sie eine Gegenpartei, eine Datei einzusenden. Sie authentifiziert sich mit dem Einmal-Einreichungs-Token — kein Konto nötig.", "pt" to "Peça a uma contraparte que envie um ficheiro. Autentica-se com o token de entrega de utilização única — sem necessidade de conta.", "it" to "Chiedi a una controparte di inviare un file. Si autentica con il token di invio monouso — nessun account necessario.", "ja" to "相手方にファイルの送付を依頼します。相手は使い捨ての提出トークンで認証します — アカウントは不要です。", "zh" to "请对方发送文件。对方使用一次性提交令牌进行验证 — 无需账户。", "hi" to "किसी प्रतिपक्ष से फ़ाइल भेजने को कहें। वे एक-बार वाले सबमिट टोकन से प्रमाणित होते हैं — किसी खाते की आवश्यकता नहीं।", "ar" to "اطلب من الطرف المقابل إرسال ملف. يجري التحقق منه برمز التسليم أحادي الاستخدام — دون حاجة إلى حساب."),
        "ntr.read" to mapOf("en" to "Read sealed file", "es" to "Leer el archivo sellado", "fr" to "Lire le fichier scellé", "de" to "Versiegelte Datei lesen", "pt" to "Ler o ficheiro selado", "it" to "Leggi il file sigillato", "ja" to "封印されたファイルを読む", "zh" to "读取封存文件", "hi" to "सीलबंद फ़ाइल पढ़ें", "ar" to "قراءة الملف المختوم"),
        "ntr.revoke" to mapOf("en" to "Revoke access", "es" to "Revocar el acceso", "fr" to "Révoquer l'accès", "de" to "Zugriff widerrufen", "pt" to "Revogar o acesso", "it" to "Revoca l'accesso", "ja" to "アクセスを取り消す", "zh" to "撤销访问权", "hi" to "पहुँच निरस्त करें", "ar" to "إلغاء الوصول"),
        "ntr.t.intake" to mapOf("en" to "Intake", "es" to "Recepción", "fr" to "Réception", "de" to "Eingang", "pt" to "Receção", "it" to "In entrata", "ja" to "受付", "zh" to "接收", "hi" to "प्राप्ति", "ar" to "استلام"),
        "ntr.t.outbound" to mapOf("en" to "Outbound", "es" to "Salientes", "fr" to "Sortants", "de" to "Ausgehend", "pt" to "Enviados", "it" to "In uscita", "ja" to "送信", "zh" to "发出", "hi" to "भेजे गए", "ar" to "صادر"),
        "offline.title" to mapOf("en" to "What this deployment can reach", "es" to "Qué puede alcanzar esta instalación", "fr" to "Ce que ce déploiement peut atteindre", "de" to "Was diese Installation erreichen kann", "pt" to "O que esta instalação pode alcançar", "it" to "Cosa può raggiungere questa installazione", "ja" to "この環境が接続できる範囲", "zh" to "此部署可以连接到什么", "hi" to "यह परिनियोजन किस तक पहुँच सकता है", "ar" to "ما يمكن أن يصل إليه هذا النشر"),
        "offline.on" to mapOf("en" to "Offline — nothing leaves this machine", "es" to "Sin conexión — nada sale de esta máquina", "fr" to "Hors ligne — rien ne quitte cette machine", "de" to "Offline — nichts verlässt diesen Rechner", "pt" to "Offline — nada sai desta máquina", "it" to "Offline — nulla esce da questa macchina", "ja" to "オフライン — このマシンから何も出ません", "zh" to "离线 — 任何内容都不会离开这台机器", "hi" to "ऑफ़लाइन — इस मशीन से कुछ भी बाहर नहीं जाता", "ar" to "دون اتصال — لا شيء يغادر هذا الجهاز"),
        "offline.off" to mapOf("en" to "Online — this deployment can reach other machines", "es" to "En línea — esta instalación puede alcanzar otras máquinas", "fr" to "En ligne — ce déploiement peut atteindre d’autres machines", "de" to "Online — diese Installation kann andere Rechner erreichen", "pt" to "Online — esta instalação pode alcançar outras máquinas", "it" to "Online — questa installazione può raggiungere altre macchine", "ja" to "オンライン — この環境は他のマシンに接続できます", "zh" to "在线 — 此部署可以连接其他机器", "hi" to "ऑनलाइन — यह परिनियोजन अन्य मशीनों तक पहुँच सकता है", "ar" to "متصل — يمكن لهذا النشر الوصول إلى أجهزة أخرى"),
        "wel.title" to mapOf("en" to "Sign in to your vault", "es" to "Entra en tu bóveda", "fr" to "Connectez-vous à votre coffre", "de" to "Melde dich an deinem Tresor an", "pt" to "Entre no seu cofre", "it" to "Accedi alla tua cassaforte", "ja" to "保管庫にサインインする", "zh" to "登录你的保险库", "hi" to "अपने वॉल्ट में साइन इन करें", "ar" to "سجّل الدخول إلى خزنتك"),
        "wel.sub" to mapOf("en" to "Paste the tenant token you were issued. It authorizes every call and never leaves this device unencrypted in transit.", "es" to "Pega el token de inquilino que se te entregó. Autoriza cada llamada y nunca sale de este dispositivo sin cifrar.", "fr" to "Collez le jeton de locataire qui vous a été remis. Il autorise chaque appel et ne quitte jamais cet appareil en clair.", "de" to "Füge das dir ausgestellte Mandanten-Token ein. Es autorisiert jeden Aufruf und verlässt dieses Gerät nie unverschlüsselt.", "pt" to "Cole o token de inquilino que lhe foi entregue. Autoriza cada chamada e nunca sai deste dispositivo sem cifra.", "it" to "Incolla il token del tenant che ti è stato rilasciato. Autorizza ogni chiamata e non lascia mai questo dispositivo in chiaro.", "ja" to "発行されたテナントトークンを貼り付けてください。すべての呼び出しを認可するもので、暗号化されないままこの端末を出ることはありません。", "zh" to "粘贴你收到的租户令牌。它为每一次调用授权，并且绝不会以未加密的形式离开这台设备。", "hi" to "आपको जारी किया गया टेनेंट टोकन यहाँ चिपकाइए। यह हर कॉल को अधिकृत करता है और बिना कूटलेखन के इस डिवाइस से कभी बाहर नहीं जाता।", "ar" to "الصق رمز المستأجر الذي صدر لك. فهو يخوّل كل نداء، ولا يغادر هذا الجهاز غير مُعمّى أبدًا."),
        "wel.token" to mapOf("en" to "Vault token", "es" to "Token de la bóveda", "fr" to "Jeton du coffre", "de" to "Tresor-Token", "pt" to "Token do cofre", "it" to "Token della cassaforte", "ja" to "保管庫のトークン", "zh" to "保险库令牌", "hi" to "वॉल्ट टोकन", "ar" to "رمز الخزنة"),
        "wel.server" to mapOf("en" to "Server", "es" to "Servidor", "fr" to "Serveur", "de" to "Server", "pt" to "Servidor", "it" to "Server", "ja" to "サーバー", "zh" to "服务器", "hi" to "सर्वर", "ar" to "الخادم"),
        "wel.tenantkey" to mapOf("en" to "Customer key (only if you hold your own)", "es" to "Clave del cliente (solo si guardas la tuya)", "fr" to "Clé client (seulement si vous détenez la vôtre)", "de" to "Kundenschlüssel (nur wenn Sie Ihren eigenen halten)", "pt" to "Chave do cliente (só se guardar a sua)", "it" to "Chiave del cliente (solo se tieni la tua)", "ja" to "顧客鍵（自分で保管している場合のみ）", "zh" to "客户密钥（仅当您自行保管时）", "hi" to "ग्राहक कुंजी (केवल यदि आप अपनी स्वयं रखते हैं)", "ar" to "مفتاح العميل (فقط إذا كنت تحتفظ بمفتاحك)"),
        "wel.tenantkey.ph" to mapOf("en" to "base64 32-byte key — sent with every request, stored nowhere", "es" to "clave de 32 bytes en base64: se envía en cada solicitud, no se guarda", "fr" to "clé de 32 octets en base64 — envoyée à chaque requête, jamais stockée", "de" to "32-Byte-Schlüssel in Base64 — bei jeder Anfrage gesendet, nirgends gespeichert", "pt" to "chave de 32 bytes em base64 — enviada em cada pedido, nunca guardada", "it" to "chiave da 32 byte in base64 — inviata a ogni richiesta, mai memorizzata", "ja" to "base64 の 32 バイト鍵 — すべてのリクエストで送信、保存はしません", "zh" to "base64 编码的 32 字节密钥 — 每个请求都发送，不做存储", "hi" to "base64 में 32-बाइट कुंजी — हर अनुरोध के साथ भेजी जाती है, संग्रहीत नहीं", "ar" to "مفتاح 32 بايت بترميز base64 — يُرسل مع كل طلب ولا يُخزَّن"),
        "wel.language" to mapOf("en" to "Language", "es" to "Idioma", "fr" to "Langue", "de" to "Sprache", "pt" to "Idioma", "it" to "Lingua", "ja" to "言語", "zh" to "语言", "hi" to "भाषा", "ar" to "اللغة"),
        "wel.unlock" to mapOf("en" to "Unlock", "es" to "Desbloquear", "fr" to "Déverrouiller", "de" to "Entsperren", "pt" to "Desbloquear", "it" to "Sblocca", "ja" to "解錠する", "zh" to "解锁", "hi" to "खोलें", "ar" to "افتح القفل"),
        "wel.backend" to mapOf("en" to "Start the backend:", "es" to "Arranca el servidor:", "fr" to "Démarrez le serveur :", "de" to "Starte das Backend:", "pt" to "Inicie o servidor:", "it" to "Avvia il backend:", "ja" to "バックエンドを起動：", "zh" to "启动后端：", "hi" to "बैकएंड शुरू कीजिए:", "ar" to "شغّل الخادم:"),
        "tab.overview" to mapOf(
            "en" to "Overview", "es" to "Resumen", "fr" to "Aperçu",
            "de" to "Übersicht", "pt" to "Visão geral", "it" to "Panoramica",
            "ja" to "概要", "zh" to "概览", "hi" to "अवलोकन", "ar" to "نظرة عامة"),
        "tab.vault" to mapOf(
            "en" to "Vault", "es" to "Bóveda", "fr" to "Coffre",
            "de" to "Tresor", "pt" to "Cofre", "it" to "Cassaforte",
            "ja" to "保管庫", "zh" to "保险库", "hi" to "वॉल्ट", "ar" to "الخزنة"),
        "tab.audit" to mapOf(
            "en" to "Audit", "es" to "Auditoría", "fr" to "Audit",
            "de" to "Audit", "pt" to "Auditoria", "it" to "Audit",
            "ja" to "監査", "zh" to "审计", "hi" to "ऑडिट", "ar" to "تدقيق"),
        "tab.sources" to mapOf(
            "en" to "Sources", "es" to "Fuentes", "fr" to "Sources",
            "de" to "Quellen", "pt" to "Fontes", "it" to "Fonti",
            "ja" to "ソース", "zh" to "来源", "hi" to "स्रोत", "ar" to "المصادر"),
        "tab.transfers" to mapOf(
            "en" to "Transfers", "es" to "Transferencias", "fr" to "Transferts",
            "de" to "Übertragungen", "pt" to "Transferências", "it" to "Trasferimenti",
            "ja" to "転送", "zh" to "传输", "hi" to "स्थानांतरण", "ar" to "التحويلات"),
        "action.sign_out" to mapOf(
            "en" to "Sign out", "es" to "Cerrar sesión", "fr" to "Se déconnecter",
            "de" to "Abmelden", "pt" to "Sair", "it" to "Esci",
            "ja" to "サインアウト", "zh" to "退出登录", "hi" to "साइन आउट",
            "ar" to "تسجيل الخروج"),
    )
}
