package com.pdi.vault

import android.content.res.Resources

/**
 * App-chrome localization: tab names and the most common actions, in every
 * language the backend supports. PDI's explanatory notes are localized
 * server-side by the tenant's language setting; this table covers the frame
 * around them. Missing keys fall back to English.
 */
object L10n {
    fun t(key: String, lang: String): String =
        table[key]?.let { it[lang] ?: it["en"] } ?: key

    val supported = listOf("en", "es", "fr", "de", "pt", "it", "ja", "zh",
                           "hi", "ar")

    /**
     * The language of somebody who has no account to take one from.
     *
     * `AppState.language` comes from the stored setting and is "en" until an
     * account exists. Every sentence the backend composes on a public route is
     * chosen from `Accept-Language`, and this shell was sending no such header
     * — the phone has been carrying the answer in the system configuration all
     * along.
     *
     * Region dropped; anything this app does not carry falls back to English
     * rather than guessing.
     */
    fun deviceLanguage(): String {
        val locales = Resources.getSystem().configuration.locales
        for (i in 0 until locales.size()) {
            val base = locales[i].language.lowercase()
            if (supported.contains(base)) return base
        }
        return "en"
    }

    private val table: Map<String, Map<String, String>> = mapOf(
        "ns.acc" to mapOf("en" to "Accessibility", "es" to "Accesibilidad", "fr" to "Accessibilité", "de" to "Barrierefreiheit", "pt" to "Acessibilidade", "it" to "Accessibilità", "ja" to "アクセシビリティ", "zh" to "无障碍", "hi" to "सुलभता", "ar" to "إمكانية الوصول"),
        "ns.acc.lead" to mapOf("en" to "Ability is not a gate. Three questions — no account, no diagnosis, no name. Your words stay on this deployment and become tracked work.", "es" to "La capacidad no es una puerta. Tres preguntas: sin cuenta, sin diagnóstico, sin nombre. Tus palabras se quedan en esta instalación y se convierten en trabajo registrado.", "fr" to "La capacité n’est pas une barrière. Trois questions — pas de compte, pas de diagnostic, pas de nom. Vos mots restent sur cette installation et deviennent du travail suivi.", "de" to "Fähigkeit ist kein Tor. Drei Fragen — kein Konto, keine Diagnose, kein Name. Deine Worte bleiben auf dieser Installation und werden zu verfolgter Arbeit.", "pt" to "Capacidade não é um portão. Três perguntas — sem conta, sem diagnóstico, sem nome. Suas palavras ficam nesta instalação e viram trabalho registrado.", "it" to "L’abilità non è un cancello. Tre domande: niente account, niente diagnosi, niente nome. Le tue parole restano su questa installazione e diventano lavoro tracciato.", "ja" to "能力は門ではありません。質問は3つ — アカウントも診断名も名前も不要です。あなたの言葉はこの環境にとどまり、追跡される作業になります。", "zh" to "能力不是门槛。三个问题——无需账户、无需诊断、无需姓名。你的话留在此部署中，并成为被追踪的工作。", "hi" to "क्षमता कोई द्वार नहीं है। तीन प्रश्न — न खाता, न निदान, न नाम। आपके शब्द इसी परिनियोजन में रहते हैं और दर्ज कार्य बन जाते हैं।", "ar" to "القدرة ليست بوابة. ثلاثة أسئلة — لا حساب ولا تشخيص ولا اسم. تبقى كلماتك على هذا النشر وتصبح عملًا متتبعًا."),
        "ns.acc.needs.title" to mapOf("en" to "Who is expected here", "es" to "A quién esperamos aquí", "fr" to "Qui est attendu ici", "de" to "Wer hier erwartet wird", "pt" to "Quem é esperado aqui", "it" to "Chi è atteso qui", "ja" to "ここに来ることが想定されている人", "zh" to "这里期待谁的到来", "hi" to "यहाँ किनकी अपेक्षा है", "ar" to "من ننتظر هنا"),
        "ns.acc.needs.blind" to mapOf("en" to "Blind and low-vision: every function works by text, images carry descriptions, and the screens use standard controls a screen reader can walk.", "es" to "Personas ciegas o con baja visión: cada función opera por texto, las imágenes llevan descripciones y las pantallas usan controles estándar que un lector de pantalla puede recorrer.", "fr" to "Personnes aveugles ou malvoyantes : chaque fonction passe par le texte, les images portent des descriptions et les écrans utilisent des contrôles standard qu’un lecteur d’écran peut parcourir.", "de" to "Blinde und sehbehinderte Menschen: jede Funktion geht über Text, Bilder tragen Beschreibungen, und die Oberfläche nutzt Standard-Elemente, die ein Screenreader ablaufen kann.", "pt" to "Pessoas cegas ou com baixa visão: toda função opera por texto, as imagens têm descrições e as telas usam controles padrão que um leitor de tela consegue percorrer.", "it" to "Persone cieche o ipovedenti: ogni funzione passa dal testo, le immagini hanno descrizioni e le schermate usano controlli standard che uno screen reader può percorrere.", "ja" to "全盲・弱視の方：すべての機能はテキストで使え、画像には説明が付き、画面はスクリーンリーダーがたどれる標準コントロールでできています。", "zh" to "盲人和低视力者：一切功能都可通过文字完成，图像带有描述，界面使用屏幕阅读器可以遍历的标准控件。", "hi" to "दृष्टिहीन और कम दृष्टि वाले: हर कार्य पाठ से होता है, चित्रों के साथ विवरण है, और स्क्रीन में मानक नियंत्रण हैं जिन्हें स्क्रीन रीडर पढ़ सकता है।", "ar" to "المكفوفون وضعاف البصر: كل وظيفة تعمل بالنص، والصور تحمل أوصافًا، والشاشات تستخدم عناصر قياسية يستطيع قارئ الشاشة تتبعها."),
        "ns.acc.needs.deaf" to mapOf("en" to "Deaf and hard of hearing: nothing here requires sound — voice is always optional, never the only way.", "es" to "Personas sordas o con pérdida auditiva: nada aquí requiere sonido; la voz es siempre opcional, nunca el único camino.", "fr" to "Personnes sourdes ou malentendantes : rien ici n’exige de son — la voix est toujours facultative, jamais le seul chemin.", "de" to "Gehörlose und schwerhörige Menschen: nichts hier verlangt Ton — Sprache ist immer optional, nie der einzige Weg.", "pt" to "Pessoas surdas ou com perda auditiva: nada aqui exige som — a voz é sempre opcional, nunca o único caminho.", "it" to "Persone sorde o con perdita d’udito: niente qui richiede l’audio — la voce è sempre facoltativa, mai l’unica via.", "ja" to "ろう・難聴の方：ここでは音を必要とするものはありません。音声は常に任意で、唯一の手段になることはありません。", "zh" to "聋人和听障者：这里没有任何功能依赖声音——语音永远是可选的，绝不是唯一途径。", "hi" to "बधिर और कम सुनने वाले: यहाँ किसी चीज़ के लिए ध्वनि आवश्यक नहीं — आवाज़ हमेशा वैकल्पिक है, कभी एकमात्र रास्ता नहीं।", "ar" to "الصم وضعاف السمع: لا شيء هنا يتطلب صوتًا — الصوت اختياري دائمًا، وليس الطريق الوحيد أبدًا."),
        "ns.acc.needs.mute" to mapOf("en" to "Mute and nonspeaking: nothing here requires speaking — anywhere a microphone is offered, typing does the same job.", "es" to "Personas mudas o que no hablan: nada aquí requiere hablar; donde se ofrece un micrófono, escribir hace el mismo trabajo.", "fr" to "Personnes muettes ou non verbales : rien ici n’exige de parler — partout où un micro est proposé, écrire fait le même travail.", "de" to "Stumme und nicht sprechende Menschen: nichts hier verlangt Sprechen — überall, wo ein Mikrofon angeboten wird, tut Tippen denselben Dienst.", "pt" to "Pessoas mudas ou não falantes: nada aqui exige falar — onde houver microfone, digitar faz o mesmo trabalho.", "it" to "Persone mute o non parlanti: niente qui richiede di parlare — ovunque ci sia un microfono, scrivere fa lo stesso lavoro.", "ja" to "発話しない方・発話が難しい方：ここでは話すことを必要とするものはありません。マイクがある場所ではどこでも、入力が同じ役割を果たします。", "zh" to "失语和不说话的人：这里没有任何功能要求开口——凡是提供麦克风的地方，打字都能完成同样的事。", "hi" to "मूक और न बोलने वाले: यहाँ बोलना आवश्यक नहीं — जहाँ भी माइक्रोफ़ोन है, वहाँ टाइप करना वही काम करता है।", "ar" to "البُكم ومن لا يتكلمون: لا شيء هنا يتطلب الكلام — أينما وُجد ميكروفون، تقوم الكتابة بالمهمة نفسها."),
        "ns.acc.needs.motor" to mapOf("en" to "Limited mobility, amputation, tremor: every control is a standard element the keyboard alone can reach, and no step in this console is timed.", "es" to "Movilidad reducida, amputación, temblor: cada control es un elemento estándar alcanzable solo con el teclado, y ningún paso de esta consola tiene límite de tiempo.", "fr" to "Mobilité réduite, amputation, tremblement : chaque contrôle est un élément standard atteignable au clavier seul, et aucune étape de cette console n’est chronométrée.", "de" to "Eingeschränkte Mobilität, Amputation, Tremor: jedes Element ist ein Standard-Element, das die Tastatur allein erreicht, und kein Schritt in dieser Konsole hat ein Zeitlimit.", "pt" to "Mobilidade reduzida, amputação, tremor: todo controle é um elemento padrão alcançável só pelo teclado, e nenhum passo neste console é cronometrado.", "it" to "Mobilità ridotta, amputazione, tremore: ogni controllo è un elemento standard raggiungibile con la sola tastiera, e nessun passaggio in questa console è a tempo.", "ja" to "運動機能の制約・切断・振戦のある方：すべてのコントロールはキーボードだけで届く標準要素で、このコンソールに制限時間のある操作はありません。", "zh" to "行动不便、截肢、震颤者：每个控件都是仅用键盘即可到达的标准元素，本控制台没有任何限时步骤。", "hi" to "सीमित गतिशीलता, अंग-विच्छेद, कंपन: हर नियंत्रण एक मानक तत्व है जिस तक केवल कीबोर्ड से पहुँचा जा सकता है, और इस कंसोल में कोई चरण समयबद्ध नहीं है।", "ar" to "محدودية الحركة والبتر والرُعاش: كل عنصر تحكم قياسي تصل إليه لوحة المفاتيح وحدها، ولا خطوة في هذه الواجهة مقيدة بوقت."),
        "ns.acc.needs.cognitive" to mapOf("en" to "Autistic and cognitively different people: plain words, one step at a time, nothing flashes, and asking again is always free.", "es" to "Personas autistas y cognitivamente diversas: palabras llanas, un paso a la vez, nada parpadea, y volver a preguntar es siempre gratis.", "fr" to "Personnes autistes et cognitivement différentes : des mots simples, une étape à la fois, rien ne clignote, et redemander est toujours gratuit.", "de" to "Autistische und kognitiv verschiedene Menschen: einfache Worte, ein Schritt nach dem anderen, nichts blinkt, und noch einmal fragen kostet nie etwas.", "pt" to "Pessoas autistas e cognitivamente diversas: palavras simples, um passo de cada vez, nada pisca, e perguntar de novo é sempre grátis.", "it" to "Persone autistiche e cognitivamente diverse: parole semplici, un passo alla volta, niente lampeggia, e chiedere di nuovo non costa mai nulla.", "ja" to "自閉スペクトラムの方・認知の仕方が異なる方：平易な言葉、一度にひとつの手順、点滅するものはなく、もう一度尋ねることはいつでも自由です。", "zh" to "自闭症和认知方式不同的人：语言平实，一次一步，没有闪烁的内容，再问一遍永远无妨。", "hi" to "ऑटिस्टिक और संज्ञानात्मक रूप से भिन्न लोग: सरल शब्द, एक समय में एक कदम, कुछ नहीं चमकता, और दोबारा पूछना हमेशा निःशुल्क है।", "ar" to "المصابون بالتوحد والمختلفون إدراكيًا: كلمات بسيطة، خطوة واحدة في كل مرة، لا شيء يومض، والسؤال مرة أخرى مجاني دائمًا."),
        "ns.acc.needs.dyslexia" to mapOf("en" to "Dyslexia and reading differences: short sentences, real headings, and nothing that punishes rereading.", "es" to "Dislexia y diferencias de lectura: frases cortas, encabezados reales y nada que castigue releer.", "fr" to "Dyslexie et différences de lecture : phrases courtes, vrais titres, et rien qui punisse la relecture.", "de" to "Dyslexie und Leseunterschiede: kurze Sätze, echte Überschriften, und nichts bestraft erneutes Lesen.", "pt" to "Dislexia e diferenças de leitura: frases curtas, títulos de verdade e nada que puna reler.", "it" to "Dislessia e differenze di lettura: frasi brevi, titoli veri e niente che punisca il rileggere.", "ja" to "ディスレクシア・読み方の異なる方：短い文、本物の見出し、読み返しても不利にならない画面。", "zh" to "阅读障碍者：短句、真实的标题，重读不会受到任何惩罚。", "hi" to "डिस्लेक्सिया और पढ़ने की भिन्नताएँ: छोटे वाक्य, वास्तविक शीर्षक, और दोबारा पढ़ने पर कोई दंड नहीं।", "ar" to "عسر القراءة وفروق القراءة: جمل قصيرة وعناوين حقيقية ولا شيء يعاقب على إعادة القراءة."),
        "ns.acc.needs.motion" to mapOf("en" to "Motion sensitivity: when your device asks for reduced motion, this console stops animating.", "es" to "Sensibilidad al movimiento: cuando tu dispositivo pide movimiento reducido, esta consola deja de animar.", "fr" to "Sensibilité au mouvement : quand votre appareil demande une animation réduite, cette console cesse d’animer.", "de" to "Bewegungsempfindlichkeit: wenn dein Gerät reduzierte Bewegung verlangt, hört diese Konsole auf zu animieren.", "pt" to "Sensibilidade a movimento: quando seu dispositivo pede movimento reduzido, este console para de animar.", "it" to "Sensibilità al movimento: quando il tuo dispositivo chiede movimento ridotto, questa console smette di animare.", "ja" to "動きに敏感な方：端末が「視差効果を減らす」を求めると、このコンソールはアニメーションを止めます。", "zh" to "对动态敏感者：当你的设备要求减少动态效果时，本控制台会停止动画。", "hi" to "गति के प्रति संवेदनशीलता: जब आपका उपकरण कम गति माँगता है, यह कंसोल एनिमेशन बंद कर देता है।", "ar" to "الحساسية للحركة: عندما يطلب جهازك تقليل الحركة، تتوقف هذه الواجهة عن التحريك."),
        "ns.acc.needs.more" to mapOf("en" to "Not on this list? The gap is in the list, not in you. Name it below and it becomes our work.", "es" to "¿No estás en esta lista? El vacío está en la lista, no en ti. Nómbralo abajo y se convierte en nuestro trabajo.", "fr" to "Pas sur cette liste ? Le manque est dans la liste, pas en vous. Nommez-le ci-dessous et cela devient notre travail.", "de" to "Nicht auf dieser Liste? Die Lücke ist in der Liste, nicht in dir. Benenne sie unten, und sie wird unsere Arbeit.", "pt" to "Não está nesta lista? A lacuna está na lista, não em você. Nomeie-a abaixo e ela vira nosso trabalho.", "it" to "Non sei in questa lista? La lacuna è nella lista, non in te. Nominala qui sotto e diventa il nostro lavoro.", "ja" to "この一覧にありませんか？足りないのは一覧であって、あなたではありません。下で名前を付けてください。それが私たちの仕事になります。", "zh" to "不在这份清单上？缺的是清单，不是你。在下方写出来，它就成为我们的工作。", "hi" to "इस सूची में नहीं हैं? कमी सूची में है, आप में नहीं। नीचे उसे नाम दें और वह हमारा काम बन जाएगा।", "ar" to "لست في هذه القائمة؟ النقص في القائمة لا فيك. اذكره أدناه وسيصبح عملنا."),
        "ns.acc.doing.ph" to mapOf("en" to "What were you trying to do?", "es" to "¿Qué intentabas hacer?", "fr" to "Qu’essayiez-vous de faire ?", "de" to "Was hast du versucht zu tun?", "pt" to "O que você estava tentando fazer?", "it" to "Cosa stavi cercando di fare?", "ja" to "何をしようとしていましたか？", "zh" to "你当时想做什么？", "hi" to "आप क्या करने की कोशिश कर रहे थे?", "ar" to "ما الذي كنت تحاول فعله؟"),
        "ns.acc.wall.ph" to mapOf("en" to "What stood in the way?", "es" to "¿Qué se interpuso?", "fr" to "Qu’est-ce qui a fait obstacle ?", "de" to "Was stand im Weg?", "pt" to "O que ficou no caminho?", "it" to "Cosa ti ha ostacolato?", "ja" to "何が妨げになりましたか？", "zh" to "是什么挡住了你？", "hi" to "क्या आड़े आया?", "ar" to "ما الذي وقف في الطريق؟"),
        "ns.acc.help.ph" to mapOf("en" to "What would help? (optional)", "es" to "¿Qué ayudaría? (opcional)", "fr" to "Qu’est-ce qui aiderait ? (facultatif)", "de" to "Was würde helfen? (optional)", "pt" to "O que ajudaria? (opcional)", "it" to "Cosa aiuterebbe? (facoltativo)", "ja" to "何があれば助かりますか？（任意）", "zh" to "什么会有帮助？（可选）", "hi" to "क्या मदद करेगा? (वैकल्पिक)", "ar" to "ما الذي قد يساعد؟ (اختياري)"),
        "ns.acc.send" to mapOf("en" to "Send report", "es" to "Enviar informe", "fr" to "Envoyer le signalement", "de" to "Bericht senden", "pt" to "Enviar relato", "it" to "Invia la segnalazione", "ja" to "報告を送る", "zh" to "发送报告", "hi" to "रिपोर्ट भेजें", "ar" to "أرسل البلاغ"),
        "ns.acc.sent" to mapOf("en" to "Received — thank you.", "es" to "Recibido. Gracias.", "fr" to "Reçu — merci.", "de" to "Angekommen — danke.", "pt" to "Recebido — obrigado.", "it" to "Ricevuto — grazie.", "ja" to "受け取りました。ありがとうございます。", "zh" to "已收到——谢谢。", "hi" to "प्राप्त हुआ — धन्यवाद।", "ar" to "وصل البلاغ — شكرًا لك."),
        "ns.acc.token.ph" to mapOf("en" to "Reviewer token", "es" to "Token de revisor", "fr" to "Jeton de réviseur", "de" to "Prüfer-Token", "pt" to "Token de revisor", "it" to "Token del revisore", "ja" to "レビュアートークン", "zh" to "审阅者令牌", "hi" to "समीक्षक टोकन", "ar" to "رمز المراجع"),
        "ns.acc.load" to mapOf("en" to "Load reports", "es" to "Cargar informes", "fr" to "Charger les signalements", "de" to "Berichte laden", "pt" to "Carregar relatos", "it" to "Carica le segnalazioni", "ja" to "報告を読み込む", "zh" to "载入报告", "hi" to "रिपोर्टें लोड करें", "ar" to "حمّل البلاغات"),
        "ns.acc.none" to mapOf("en" to "No reports yet.", "es" to "Aún no hay informes.", "fr" to "Aucun signalement pour l’instant.", "de" to "Noch keine Berichte.", "pt" to "Ainda não há relatos.", "it" to "Ancora nessuna segnalazione.", "ja" to "まだ報告はありません。", "zh" to "还没有报告。", "hi" to "अभी कोई रिपोर्ट नहीं।", "ar" to "لا بلاغات بعد."),
        "nacc.handle" to mapOf("en" to "Handle (optional)", "es" to "Identificador (opcional)", "fr" to "Identifiant (facultatif)", "de" to "Kennung (optional)", "pt" to "Identificador (opcional)", "it" to "Handle (facoltativo)", "ja" to "ハンドル（任意）", "zh" to "用户名（可选）", "hi" to "हैंडल (वैकल्पिक)", "ar" to "المعرّف (اختياري)"),
        "nacc.handle.ph" to mapOf("en" to "@account", "es" to "@cuenta", "fr" to "@compte", "de" to "@konto", "pt" to "@conta", "it" to "@account", "ja" to "@アカウント", "zh" to "@账户", "hi" to "@खाता", "ar" to "@حساب"),
        "nacc.id.ph" to mapOf("en" to "pdi_…", "es" to "pdi_…", "fr" to "pdi_…", "de" to "pdi_…", "pt" to "pdi_…", "it" to "pdi_…", "ja" to "pdi_…", "zh" to "pdi_…", "hi" to "pdi_…", "ar" to "pdi_…"),
        "nadm.retire" to mapOf("en" to "Retire old", "es" to "Retirar la anterior", "fr" to "Retirer l'ancienne", "de" to "Alte zurückziehen", "pt" to "Retirar a anterior", "it" to "Ritira la vecchia", "ja" to "旧鍵を廃止", "zh" to "停用旧密钥", "hi" to "पुरानी हटाएँ", "ar" to "سحب القديم"),
        "nadm.rotate" to mapOf("en" to "Rotate key", "es" to "Rotar la clave", "fr" to "Faire tourner la clé", "de" to "Schlüssel rotieren", "pt" to "Rodar a chave", "it" to "Ruota la chiave", "ja" to "鍵をローテーション", "zh" to "轮换密钥", "hi" to "कुंजी घुमाएँ", "ar" to "تدوير المفتاح"),
        "nadm.token" to mapOf("en" to "Admin token", "es" to "Token de administrador", "fr" to "Jeton d'administration", "de" to "Admin-Token", "pt" to "Token de administrador", "it" to "Token di amministrazione", "ja" to "管理者トークン", "zh" to "管理员令牌", "hi" to "एडमिन टोकन", "ar" to "رمز المشرف"),
        "nadm.versions" to mapOf("en" to "Load versions", "es" to "Cargar versiones", "fr" to "Charger les versions", "de" to "Versionen laden", "pt" to "Carregar versões", "it" to "Carica le versioni", "ja" to "バージョンを読み込む", "zh" to "加载版本", "hi" to "संस्करण लोड करें", "ar" to "تحميل الإصدارات"),
        "nfb.msg.ph" to mapOf("en" to "What's on your mind?", "es" to "¿Qué te preocupa?", "fr" to "Qu'avez-vous en tête ?", "de" to "Was beschäftigt Sie?", "pt" to "O que lhe vai na cabeça?", "it" to "A cosa stai pensando?", "ja" to "気になっていることは？", "zh" to "你在想什么？", "hi" to "आपके मन में क्या है?", "ar" to "بماذا تفكر؟"),
        "nfb.send" to mapOf("en" to "Send feedback", "es" to "Enviar comentarios", "fr" to "Envoyer un retour", "de" to "Rückmeldung senden", "pt" to "Enviar comentários", "it" to "Invia un riscontro", "ja" to "フィードバックを送る", "zh" to "发送反馈", "hi" to "प्रतिक्रिया भेजें", "ar" to "إرسال ملاحظات"),
        "nfil.content" to mapOf("en" to "Content", "es" to "Contenido", "fr" to "Contenu", "de" to "Inhalt", "pt" to "Conteúdo", "it" to "Contenuto", "ja" to "内容", "zh" to "内容", "hi" to "सामग्री", "ar" to "المحتوى"),
        "nfil.content.ph" to mapOf("en" to "the file body to seal", "es" to "el cuerpo del archivo a sellar", "fr" to "le corps du fichier à sceller", "de" to "der zu versiegelnde Dateiinhalt", "pt" to "o corpo do ficheiro a selar", "it" to "il corpo del file da sigillare", "ja" to "封印するファイル本文", "zh" to "要封存的文件正文", "hi" to "सील करने हेतु फ़ाइल सामग्री", "ar" to "محتوى الملف المراد ختمه"),
        "nfil.filename" to mapOf("en" to "Filename", "es" to "Nombre de archivo", "fr" to "Nom du fichier", "de" to "Dateiname", "pt" to "Nome do ficheiro", "it" to "Nome del file", "ja" to "ファイル名", "zh" to "文件名", "hi" to "फ़ाइल नाम", "ar" to "اسم الملف"),
        "nfil.filename.ph" to mapOf("en" to "e.g. results.pdf", "es" to "p. ej. resultados.pdf", "fr" to "ex. resultats.pdf", "de" to "z. B. ergebnisse.pdf", "pt" to "p. ex. resultados.pdf", "it" to "es. risultati.pdf", "ja" to "例：results.pdf", "zh" to "例如：results.pdf", "hi" to "उदा. results.pdf", "ar" to "مثال: results.pdf"),
        "nfil.programs" to mapOf("en" to "Programs", "es" to "Programas", "fr" to "Programmes", "de" to "Programme", "pt" to "Programas", "it" to "Programmi", "ja" to "プログラム", "zh" to "合规方案", "hi" to "कार्यक्रम", "ar" to "البرامج"),
        "nfil.recipient" to mapOf("en" to "Recipient", "es" to "Destinatario", "fr" to "Destinataire", "de" to "Empfänger", "pt" to "Destinatário", "it" to "Destinatario", "ja" to "受取人", "zh" to "接收人", "hi" to "प्राप्तकर्ता", "ar" to "المستلم"),
        "nfil.recipient.ph" to mapOf("en" to "who it's for", "es" to "para quién es", "fr" to "à qui c'est destiné", "de" to "für wen es ist", "pt" to "para quem é", "it" to "per chi è", "ja" to "誰宛てか", "zh" to "发送给谁", "hi" to "किसके लिए", "ar" to "لمن هو"),
        "nfil.seal" to mapOf("en" to "Seal & create", "es" to "Sellar y crear", "fr" to "Sceller et créer", "de" to "Versiegeln und anlegen", "pt" to "Selar e criar", "it" to "Sigilla e crea", "ja" to "封印して作成", "zh" to "封存并创建", "hi" to "सील करें और बनाएँ", "ar" to "ختم وإنشاء"),
        "nfil.sub" to mapOf("en" to "Seal a file for a recipient under compliance controls. Retention follows the strictest program you pick.", "es" to "Sella un archivo para un destinatario bajo controles de cumplimiento. La retención sigue el programa más estricto que elijas.", "fr" to "Scellez un fichier pour un destinataire sous contrôles de conformité. La conservation suit le programme le plus strict que vous choisissez.", "de" to "Versiegeln Sie eine Datei für einen Empfänger unter Compliance-Kontrollen. Die Aufbewahrung richtet sich nach dem strengsten Programm, das Sie wählen.", "pt" to "Sele um ficheiro para um destinatário sob controlos de conformidade. A retenção segue o programa mais estrito que escolher.", "it" to "Sigilla un file per un destinatario con controlli di conformità. La conservazione segue il programma più rigoroso che scegli.", "ja" to "コンプライアンス管理のもとで受取人向けにファイルを封印します。保持期間は選択した中で最も厳格なプログラムに従います。", "zh" to "在合规控制下为接收人封存文件。保留期限遵循你所选最严格的合规方案。", "hi" to "अनुपालन नियंत्रणों के तहत प्राप्तकर्ता के लिए फ़ाइल सील करें। प्रतिधारण आपके चुने हुए सबसे कठोर कार्यक्रम का पालन करता है।", "ar" to "اختم ملفًا لمستلم وفق ضوابط الامتثال. تتبع مدة الاحتفاظ أشدّ برنامج تختاره."),
        "nfil.token.hand" to mapOf("en" to "Hand this to the recipient out of band; it is the only way to retrieve the file.", "es" to "Entrega esto al destinatario por otro canal; es la única forma de recuperar el archivo.", "fr" to "Remettez ceci au destinataire par un autre canal ; c'est le seul moyen de récupérer le fichier.", "de" to "Übergeben Sie dies dem Empfänger über einen anderen Kanal; es ist der einzige Weg, die Datei abzurufen.", "pt" to "Entregue isto ao destinatário por outro canal; é a única forma de recuperar o ficheiro.", "it" to "Consegna questo al destinatario per un altro canale; è l'unico modo per recuperare il file.", "ja" to "これは別の経路で受取人に渡してください。ファイルを取り出す唯一の手段です。", "zh" to "请通过其他渠道将其交给接收人；这是取回该文件的唯一方式。", "hi" to "इसे प्राप्तकर्ता को किसी अन्य माध्यम से सौंपें; फ़ाइल पाने का यही एकमात्र रास्ता है।", "ar" to "سلّم هذا إلى المستلم عبر قناة أخرى؛ فهو السبيل الوحيد لاسترجاع الملف."),
        "nfil.token.once" to mapOf("en" to "Receive token — shown once", "es" to "Token de recepción: se muestra una sola vez", "fr" to "Jeton de réception — affiché une seule fois", "de" to "Empfangs-Token — nur einmal angezeigt", "pt" to "Token de receção — mostrado uma só vez", "it" to "Token di ricezione — mostrato una sola volta", "ja" to "受信トークン — 一度だけ表示されます", "zh" to "接收令牌 — 仅显示一次", "hi" to "प्राप्ति टोकन — केवल एक बार दिखाया जाता है", "ar" to "رمز الاستلام — يُعرض مرة واحدة"),
        "nint.content.ph" to mapOf("en" to "the file body", "es" to "el cuerpo del archivo", "fr" to "le corps du fichier", "de" to "der Dateiinhalt", "pt" to "o corpo do ficheiro", "it" to "il corpo del file", "ja" to "ファイル本文", "zh" to "文件正文", "hi" to "फ़ाइल सामग्री", "ar" to "محتوى الملف"),
        "nint.filename.ph" to mapOf("en" to "e.g. w2.pdf", "es" to "p. ej. w2.pdf", "fr" to "ex. w2.pdf", "de" to "z. B. w2.pdf", "pt" to "p. ex. w2.pdf", "it" to "es. w2.pdf", "ja" to "例：w2.pdf", "zh" to "例如：w2.pdf", "hi" to "उदा. w2.pdf", "ar" to "مثال: w2.pdf"),
        "nint.go" to mapOf("en" to "Submit into the newest open intake", "es" to "Entregar en la recepción abierta más reciente", "fr" to "Déposer dans la dernière collecte ouverte", "de" to "In die neueste offene Annahme einreichen", "pt" to "Entregar na receção aberta mais recente", "it" to "Invia all'ultima raccolta aperta", "ja" to "最新の受付に提出", "zh" to "提交至最新的开放受理", "hi" to "नवीनतम खुले इनटेक में जमा करें", "ar" to "الإرسال إلى أحدث استلام مفتوح"),
        "nint.token" to mapOf("en" to "Submit token", "es" to "Token de entrega", "fr" to "Jeton de dépôt", "de" to "Einreichungs-Token", "pt" to "Token de entrega", "it" to "Token di invio", "ja" to "提出トークン", "zh" to "提交令牌", "hi" to "सबमिट टोकन", "ar" to "رمز التسليم"),
        "nint.token.once" to mapOf("en" to "Submit token — shown once", "es" to "Token de entrega: se muestra una sola vez", "fr" to "Jeton de dépôt — affiché une seule fois", "de" to "Einreichungs-Token — nur einmal angezeigt", "pt" to "Token de entrega — mostrado uma só vez", "it" to "Token di invio — mostrato una sola volta", "ja" to "提出トークン — 一度だけ表示されます", "zh" to "提交令牌 — 仅显示一次", "hi" to "सबमिट टोकन — केवल एक बार दिखाया जाता है", "ar" to "رمز التسليم — يُعرض مرة واحدة"),
        "nint.token.ph" to mapOf("en" to "intk token", "es" to "token intk", "fr" to "jeton intk", "de" to "intk-Token", "pt" to "token intk", "it" to "token intk", "ja" to "intk トークン", "zh" to "intk 令牌", "hi" to "intk टोकन", "ar" to "رمز intk"),
        "nint.token.send" to mapOf("en" to "Send this to the counterparty out of band; it is their only way in.", "es" to "Envía esto a la contraparte por otro canal; es su única vía de entrada.", "fr" to "Envoyez ceci à la contrepartie par un autre canal ; c'est sa seule porte d'entrée.", "de" to "Senden Sie dies der Gegenpartei über einen anderen Kanal; es ist ihr einziger Zugang.", "pt" to "Envie isto à contraparte por outro canal; é a única entrada de que dispõe.", "it" to "Invia questo alla controparte per un altro canale; è la sua unica via d'accesso.", "ja" to "これは別の経路で相手方に送ってください。相手が入れる唯一の手段です。", "zh" to "请通过其他渠道发送给对方；这是对方唯一的进入方式。", "hi" to "इसे प्रतिपक्ष को किसी अन्य माध्यम से भेजें; उनके लिए यही एकमात्र प्रवेश है।", "ar" to "أرسل هذا إلى الطرف المقابل عبر قناة أخرى؛ فهو مدخله الوحيد."),
        "nrec.key" to mapOf("en" to "Key", "es" to "Clave", "fr" to "Clé", "de" to "Schlüssel", "pt" to "Chave", "it" to "Chiave", "ja" to "キー", "zh" to "键名", "hi" to "कुंजी", "ar" to "المفتاح"),
        "nrec.key.ph" to mapOf("en" to "e.g. ssn", "es" to "p. ej. ssn", "fr" to "ex. ssn", "de" to "z. B. ssn", "pt" to "p. ex. ssn", "it" to "es. ssn", "ja" to "例：ssn", "zh" to "例如：ssn", "hi" to "उदा. ssn", "ar" to "مثال: ssn"),
        "nrec.seal" to mapOf("en" to "Seal record", "es" to "Sellar el registro", "fr" to "Sceller l'enregistrement", "de" to "Datensatz versiegeln", "pt" to "Selar o registo", "it" to "Sigilla il record", "ja" to "レコードを封印", "zh" to "封存记录", "hi" to "रिकॉर्ड सील करें", "ar" to "ختم السجل"),
        "nrec.t.records" to mapOf("en" to "Records", "es" to "Registros", "fr" to "Enregistrements", "de" to "Datensätze", "pt" to "Registos", "it" to "Record", "ja" to "レコード", "zh" to "记录", "hi" to "रिकॉर्ड", "ar" to "السجلات"),
        "nrec.value" to mapOf("en" to "Value", "es" to "Valor", "fr" to "Valeur", "de" to "Wert", "pt" to "Valor", "it" to "Valore", "ja" to "値", "zh" to "值", "hi" to "मान", "ar" to "القيمة"),
        "nrec.value.ph" to mapOf("en" to "plaintext to seal", "es" to "texto a sellar", "fr" to "texte en clair à sceller", "de" to "zu versiegelnder Klartext", "pt" to "texto a selar", "it" to "testo in chiaro da sigillare", "ja" to "封印する平文", "zh" to "要封存的明文", "hi" to "सील करने हेतु सादा पाठ", "ar" to "نص للختم"),
        "nreq.close" to mapOf("en" to "Close request", "es" to "Cerrar la solicitud", "fr" to "Clore la demande", "de" to "Anfrage schließen", "pt" to "Fechar o pedido", "it" to "Chiudi la richiesta", "ja" to "依頼を終了する", "zh" to "关闭请求", "hi" to "अनुरोध बंद करें", "ar" to "إغلاق الطلب"),
        "nreq.from" to mapOf("en" to "From", "es" to "De", "fr" to "De", "de" to "Von", "pt" to "De", "it" to "Da", "ja" to "送信元", "zh" to "来自", "hi" to "से", "ar" to "من"),
        "nreq.from.ph" to mapOf("en" to "who should send it", "es" to "quién debe enviarlo", "fr" to "qui doit l'envoyer", "de" to "wer es senden soll", "pt" to "quem deve enviá-lo", "it" to "chi deve inviarlo", "ja" to "誰が送るべきか", "zh" to "应由谁发送", "hi" to "इसे कौन भेजे", "ar" to "من يرسله"),
        "nreq.go" to mapOf("en" to "Request file", "es" to "Solicitar archivo", "fr" to "Demander le fichier", "de" to "Datei anfordern", "pt" to "Solicitar ficheiro", "it" to "Richiedi il file", "ja" to "ファイルを依頼", "zh" to "请求文件", "hi" to "फ़ाइल का अनुरोध करें", "ar" to "طلب ملف"),
        "nreq.purpose" to mapOf("en" to "Purpose (optional)", "es" to "Motivo (opcional)", "fr" to "Objet (facultatif)", "de" to "Zweck (optional)", "pt" to "Finalidade (opcional)", "it" to "Scopo (facoltativo)", "ja" to "目的（任意）", "zh" to "用途（可选）", "hi" to "उद्देश्य (वैकल्पिक)", "ar" to "الغرض (اختياري)"),
        "nreq.purpose.ph" to mapOf("en" to "why you need it", "es" to "por qué lo necesitas", "fr" to "pourquoi vous en avez besoin", "de" to "warum Sie es brauchen", "pt" to "porque precisa dele", "it" to "perché ti serve", "ja" to "なぜ必要か", "zh" to "为什么需要它", "hi" to "आपको इसकी आवश्यकता क्यों है", "ar" to "لماذا تحتاجه"),
        "nrob.bind.go" to mapOf("en" to "Bind", "es" to "Vincular", "fr" to "Associer", "de" to "Verbinden", "pt" to "Vincular", "it" to "Collega", "ja" to "接続", "zh" to "绑定", "hi" to "जोड़ें", "ar" to "ربط"),
        "ntr.answer.sub" to mapOf("en" to "Paste an intake's submit token to answer it — this is what the counterparty does, no vault account involved.", "es" to "Pega el token de entrega de una recepción para responderla: esto es lo que hace la contraparte, sin ninguna cuenta de la bóveda.", "fr" to "Collez le jeton de dépôt d'une réception pour y répondre — c'est ce que fait la contrepartie, sans aucun compte du coffre.", "de" to "Fügen Sie das Einreichungs-Token einer Annahme ein, um sie zu beantworten — das tut die Gegenpartei, ganz ohne Tresorkonto.", "pt" to "Cole o token de entrega de uma receção para lhe responder — é o que a contraparte faz, sem qualquer conta do cofre.", "it" to "Incolla il token di invio di una ricezione per rispondere — è ciò che fa la controparte, senza alcun account del caveau.", "ja" to "受付の提出トークンを貼り付けて応答します — これは相手方が行う操作で、保管庫のアカウントは不要です。", "zh" to "粘贴接收的提交令牌以作答复 — 这是对方的操作，无需保险库账户。", "hi" to "उत्तर देने के लिए किसी प्राप्ति का सबमिट टोकन चिपकाएँ — यह प्रतिपक्ष करता है, वॉल्ट खाते की आवश्यकता नहीं।", "ar" to "الصق رمز تسليم استلامٍ للردّ عليه — هذا ما يفعله الطرف المقابل، دون أي حساب في الخزنة."),
        "ntr.as.sender" to mapOf("en" to "Act as the sender", "es" to "Actuar como remitente", "fr" to "Agir en tant qu'expéditeur", "de" to "Als Absender handeln", "pt" to "Agir como remetente", "it" to "Agisci come mittente", "ja" to "送信者として操作する", "zh" to "以发送方身份操作", "hi" to "भेजने वाले के रूप में कार्य करें", "ar" to "التصرّف بصفة المرسِل"),
        "ntr.intake" to mapOf("en" to "Secure intake", "es" to "Recepción segura", "fr" to "Réception sécurisée", "de" to "Sichere Annahme", "pt" to "Receção segura", "it" to "Ricezione sicura", "ja" to "セキュアな受付", "zh" to "安全接收", "hi" to "सुरक्षित प्राप्ति", "ar" to "استلام آمن"),
        "ntr.intake.sub" to mapOf("en" to "Ask a counterparty to send a file in. They authenticate with the one-shot submit token — no account needed.", "es" to "Pide a una contraparte que envíe un archivo. Se autentica con el token de entrega de un solo uso; no necesita cuenta.", "fr" to "Demandez à une contrepartie d'envoyer un fichier. Elle s'authentifie avec le jeton de dépôt à usage unique — aucun compte requis.", "de" to "Bitten Sie eine Gegenpartei, eine Datei einzusenden. Sie authentifiziert sich mit dem Einmal-Einreichungs-Token — kein Konto nötig.", "pt" to "Peça a uma contraparte que envie um ficheiro. Autentica-se com o token de entrega de utilização única — sem necessidade de conta.", "it" to "Chiedi a una controparte di inviare un file. Si autentica con il token di invio monouso — nessun account necessario.", "ja" to "相手方にファイルの送付を依頼します。相手は使い捨ての提出トークンで認証します — アカウントは不要です。", "zh" to "请对方发送文件。对方使用一次性提交令牌进行验证 — 无需账户。", "hi" to "किसी प्रतिपक्ष से फ़ाइल भेजने को कहें। वे एक-बार वाले सबमिट टोकन से प्रमाणित होते हैं — किसी खाते की आवश्यकता नहीं।", "ar" to "اطلب من الطرف المقابل إرسال ملف. يجري التحقق منه برمز التسليم أحادي الاستخدام — دون حاجة إلى حساب."),
        "ntr.read" to mapOf("en" to "Read sealed file", "es" to "Leer el archivo sellado", "fr" to "Lire le fichier scellé", "de" to "Versiegelte Datei lesen", "pt" to "Ler o ficheiro selado", "it" to "Leggi il file sigillato", "ja" to "封印されたファイルを読む", "zh" to "读取封存文件", "hi" to "सीलबंद फ़ाइल पढ़ें", "ar" to "قراءة الملف المختوم"),
        "ntr.revoke" to mapOf("en" to "Revoke access", "es" to "Revocar el acceso", "fr" to "Révoquer l'accès", "de" to "Zugriff widerrufen", "pt" to "Revogar o acesso", "it" to "Revoca l'accesso", "ja" to "アクセスを取り消す", "zh" to "撤销访问权", "hi" to "पहुँच निरस्त करें", "ar" to "إلغاء الوصول"),
        "ntr.t.intake" to mapOf("en" to "Intake", "es" to "Recepción", "fr" to "Réception", "de" to "Eingang", "pt" to "Receção", "it" to "In entrata", "ja" to "受付", "zh" to "接收", "hi" to "प्राप्ति", "ar" to "استلام"),
        "ntr.t.outbound" to mapOf("en" to "Outbound", "es" to "Salientes", "fr" to "Sortants", "de" to "Ausgehend", "pt" to "Enviados", "it" to "In uscita", "ja" to "送信", "zh" to "发出", "hi" to "भेजे गए", "ar" to "صادر"),
        "offline.title" to mapOf("en" to "What this deployment can reach", "es" to "Qué puede alcanzar esta instalación", "fr" to "Ce que ce déploiement peut atteindre", "de" to "Was diese Installation erreichen kann", "pt" to "O que esta instalação pode alcançar", "it" to "Cosa può raggiungere questa installazione", "ja" to "この環境が接続できる範囲", "zh" to "此部署可以连接到什么", "hi" to "यह परिनियोजन किस तक पहुँच सकता है", "ar" to "ما يمكن أن يصل إليه هذا النشر"),
        "offline.on" to mapOf("en" to "Offline — nothing leaves this machine", "es" to "Sin conexión — nada sale de esta máquina", "fr" to "Hors ligne — rien ne quitte cette machine", "de" to "Offline — nichts verlässt diesen Rechner", "pt" to "Offline — nada sai desta máquina", "it" to "Offline — nulla esce da questa macchina", "ja" to "オフライン — このマシンから何も出ません", "zh" to "离线 — 任何内容都不会离开这台机器", "hi" to "ऑफ़लाइन — इस मशीन से कुछ भी बाहर नहीं जाता", "ar" to "دون اتصال — لا شيء يغادر هذا الجهاز"),
        "offline.off" to mapOf("en" to "Online — this deployment can reach other machines", "es" to "En línea — esta instalación puede alcanzar otras máquinas", "fr" to "En ligne — ce déploiement peut atteindre d’autres machines", "de" to "Online — diese Installation kann andere Rechner erreichen", "pt" to "Online — esta instalação pode alcançar outras máquinas", "it" to "Online — questa installazione può raggiungere altre macchine", "ja" to "オンライン — この環境は他のマシンに接続できます", "zh" to "在线 — 此部署可以连接其他机器", "hi" to "ऑनलाइन — यह परिनियोजन अन्य मशीनों तक पहुँच सकता है", "ar" to "متصل — يمكن لهذا النشر الوصول إلى أجهزة أخرى"),
        "wel.title" to mapOf("en" to "Sign in to your vault", "es" to "Entra en tu bóveda", "fr" to "Connectez-vous à votre coffre", "de" to "Melde dich an deinem Tresor an", "pt" to "Entre no seu cofre", "it" to "Accedi alla tua cassaforte", "ja" to "保管庫にサインインする", "zh" to "登录你的保险库", "hi" to "अपने वॉल्ट में साइन इन करें", "ar" to "سجّل الدخول إلى خزنتك"),
        "wel.sub" to mapOf("en" to "Paste the tenant token you were issued. It authorizes every call and never leaves this device unencrypted in transit.", "es" to "Pega el token de inquilino que se te entregó. Autoriza cada llamada y nunca sale de este dispositivo sin cifrar.", "fr" to "Collez le jeton de locataire qui vous a été remis. Il autorise chaque appel et ne quitte jamais cet appareil en clair.", "de" to "Füge das dir ausgestellte Mandanten-Token ein. Es autorisiert jeden Aufruf und verlässt dieses Gerät nie unverschlüsselt.", "pt" to "Cole o token de inquilino que lhe foi entregue. Autoriza cada chamada e nunca sai deste dispositivo sem cifra.", "it" to "Incolla il token del tenant che ti è stato rilasciato. Autorizza ogni chiamata e non lascia mai questo dispositivo in chiaro.", "ja" to "発行されたテナントトークンを貼り付けてください。すべての呼び出しを認可するもので、暗号化されないままこの端末を出ることはありません。", "zh" to "粘贴你收到的租户令牌。它为每一次调用授权，并且绝不会以未加密的形式离开这台设备。", "hi" to "आपको जारी किया गया टेनेंट टोकन यहाँ चिपकाइए। यह हर कॉल को अधिकृत करता है और बिना कूटलेखन के इस डिवाइस से कभी बाहर नहीं जाता।", "ar" to "الصق رمز المستأجر الذي صدر لك. فهو يخوّل كل نداء، ولا يغادر هذا الجهاز غير مُعمّى أبدًا."),
        "wel.token" to mapOf("en" to "Vault token", "es" to "Token de la bóveda", "fr" to "Jeton du coffre", "de" to "Tresor-Token", "pt" to "Token do cofre", "it" to "Token della cassaforte", "ja" to "保管庫のトークン", "zh" to "保险库令牌", "hi" to "वॉल्ट टोकन", "ar" to "رمز الخزنة"),
        "wel.server" to mapOf("en" to "Server", "es" to "Servidor", "fr" to "Serveur", "de" to "Server", "pt" to "Servidor", "it" to "Server", "ja" to "サーバー", "zh" to "服务器", "hi" to "सर्वर", "ar" to "الخادم"),
        "wel.tenantkey" to mapOf("en" to "Customer key (only if you hold your own)", "es" to "Clave del cliente (solo si guardas la tuya)", "fr" to "Clé client (seulement si vous détenez la vôtre)", "de" to "Kundenschlüssel (nur wenn Sie Ihren eigenen halten)", "pt" to "Chave do cliente (só se guardar a sua)", "it" to "Chiave del cliente (solo se tieni la tua)", "ja" to "顧客鍵（自分で保管している場合のみ）", "zh" to "客户密钥（仅当您自行保管时）", "hi" to "ग्राहक कुंजी (केवल यदि आप अपनी स्वयं रखते हैं)", "ar" to "مفتاح العميل (فقط إذا كنت تحتفظ بمفتاحك)"),
        "wel.tenantkey.ph" to mapOf("en" to "base64 32-byte key — sent with every request, stored nowhere", "es" to "clave de 32 bytes en base64: se envía en cada solicitud, no se guarda", "fr" to "clé de 32 octets en base64 — envoyée à chaque requête, jamais stockée", "de" to "32-Byte-Schlüssel in Base64 — bei jeder Anfrage gesendet, nirgends gespeichert", "pt" to "chave de 32 bytes em base64 — enviada em cada pedido, nunca guardada", "it" to "chiave da 32 byte in base64 — inviata a ogni richiesta, mai memorizzata", "ja" to "base64 の 32 バイト鍵 — すべてのリクエストで送信、保存はしません", "zh" to "base64 编码的 32 字节密钥 — 每个请求都发送，不做存储", "hi" to "base64 में 32-बाइट कुंजी — हर अनुरोध के साथ भेजी जाती है, संग्रहीत नहीं", "ar" to "مفتاح 32 بايت بترميز base64 — يُرسل مع كل طلب ولا يُخزَّن"),
        "wel.language" to mapOf("en" to "Language", "es" to "Idioma", "fr" to "Langue", "de" to "Sprache", "pt" to "Idioma", "it" to "Lingua", "ja" to "言語", "zh" to "语言", "hi" to "भाषा", "ar" to "اللغة"),
        "wel.unlock" to mapOf("en" to "Unlock", "es" to "Desbloquear", "fr" to "Déverrouiller", "de" to "Entsperren", "pt" to "Desbloquear", "it" to "Sblocca", "ja" to "解錠する", "zh" to "解锁", "hi" to "खोलें", "ar" to "افتح القفل"),
        "wel.backend" to mapOf("en" to "Start the backend:", "es" to "Arranca el servidor:", "fr" to "Démarrez le serveur :", "de" to "Starte das Backend:", "pt" to "Inicie o servidor:", "it" to "Avvia il backend:", "ja" to "バックエンドを起動：", "zh" to "启动后端：", "hi" to "बैकएंड शुरू कीजिए:", "ar" to "شغّل الخادم:"),
        "nadm.rotated" to mapOf("en" to "Rotated — every record re-sealed under the new version.", "es" to "Rotada: todos los registros se han vuelto a sellar con la nueva versión.", "fr" to "Rotation effectuée — tous les enregistrements ont été rescellés sous la nouvelle version.", "de" to "Rotiert — jeder Datensatz wurde unter der neuen Version neu versiegelt.", "pt" to "Rodada — todos os registos foram novamente selados sob a nova versão.", "it" to "Ruotata — ogni record è stato risigillato con la nuova versione.", "ja" to "ローテーションしました — すべてのレコードを新しいバージョンで再封印しました。", "zh" to "已轮换 — 所有记录已在新版本下重新封存。", "hi" to "घुमाई गई — हर रिकॉर्ड नए संस्करण के तहत पुनः सील किया गया।", "ar" to "تم التدوير — أُعيد ختم كل سجل بالإصدار الجديد."),
        "fb.sofar" to mapOf("en" to "So far: {list}", "es" to "Hasta ahora: {list}", "fr" to "Jusqu'ici : {list}", "de" to "Bisher: {list}", "pt" to "Até agora: {list}", "it" to "Finora: {list}", "ja" to "これまで：{list}", "zh" to "目前：{list}", "hi" to "अब तक: {list}", "ar" to "حتى الآن: {list}"),
        "fb.thanks" to mapOf("en" to "Thank you — sent.", "es" to "Gracias, enviado.", "fr" to "Merci — envoyé.", "de" to "Danke — gesendet.", "pt" to "Obrigado — enviado.", "it" to "Grazie — inviato.", "ja" to "ありがとうございます — 送信しました。", "zh" to "谢谢 — 已发送。", "hi" to "धन्यवाद — भेज दिया गया।", "ar" to "شكرًا لك — تم الإرسال."),
        "prb.can" to mapOf("en" to "This app can send a count of what failed — the operation and the HTTP status, the day, and how many times. Not what you typed, not who you are, not which profile. Nothing that identifies you or anyone else.", "es" to "Esta aplicación puede enviar un recuento de lo que falló: la operación y el estado HTTP, el día y cuántas veces. No lo que escribiste, ni quién eres, ni qué inquilino. Nada que te identifique a ti ni a nadie.", "fr" to "Cette application peut envoyer un décompte des échecs : l'opération et le statut HTTP, le jour et le nombre de fois. Pas ce que vous avez saisi, ni qui vous êtes, ni quel locataire. Rien qui vous identifie, ni personne d'autre.", "de" to "Diese App kann eine Anzahl der Fehler senden — den Vorgang und den HTTP-Status, den Tag und wie oft. Nicht, was Sie eingegeben haben, nicht, wer Sie sind, nicht welcher Mandant. Nichts, was Sie oder jemand anderen identifiziert.", "pt" to "Esta aplicação pode enviar uma contagem do que falhou — a operação e o estado HTTP, o dia e quantas vezes. Não o que escreveu, nem quem é, nem que inquilino. Nada que o identifique a si ou a outra pessoa.", "it" to "Questa app può inviare un conteggio degli errori — l'operazione e lo stato HTTP, il giorno e quante volte. Non ciò che hai digitato, non chi sei, non quale tenant. Nulla che identifichi te o chiunque altro.", "ja" to "このアプリは失敗の件数を送信できます — 操作と HTTP ステータス、日付、回数です。入力した内容、あなたが誰か、どのテナントかは送りません。あなたや他の誰かを特定するものは何もありません。", "zh" to "此应用可以发送失败计数 — 操作与 HTTP 状态、日期以及次数。不包括你输入的内容、你是谁、或哪个租户。没有任何能识别你或他人的信息。", "hi" to "यह ऐप विफलताओं की गिनती भेज सकता है — कार्रवाई और HTTP स्थिति, दिन, और कितनी बार। आपने क्या टाइप किया, आप कौन हैं, कौन-सा टेनेंट — कुछ नहीं। ऐसा कुछ भी नहीं जो आपकी या किसी और की पहचान करे।", "ar" to "يمكن لهذا التطبيق إرسال عدد ما فشل — العملية وحالة HTTP واليوم وعدد المرات. لا ما كتبته، ولا من أنت، ولا أي مستأجر. لا شيء يعرّفك أو يعرّف أي شخص آخر."),
        "prb.show" to mapOf("en" to "Show what would be sent", "es" to "Ver qué se enviaría", "fr" to "Voir ce qui serait envoyé", "de" to "Anzeigen, was gesendet würde", "pt" to "Ver o que seria enviado", "it" to "Mostra cosa verrebbe inviato", "ja" to "送信される内容を表示", "zh" to "查看将要发送的内容", "hi" to "देखें क्या भेजा जाएगा", "ar" to "إظهار ما سيُرسَل"),
        "prb.hide" to mapOf("en" to "Hide what would be sent", "es" to "Ocultar qué se enviaría", "fr" to "Masquer ce qui serait envoyé", "de" to "Ausblenden, was gesendet würde", "pt" to "Ocultar o que seria enviado", "it" to "Nascondi cosa verrebbe inviato", "ja" to "送信される内容を隠す", "zh" to "隐藏将要发送的内容", "hi" to "छिपाएँ क्या भेजा जाएगा", "ar" to "إخفاء ما سيُرسَل"),
        "prb.nowhere" to mapOf("en" to "This build reports nowhere. Failures are counted on this machine and never leave it.", "es" to "Esta compilación no informa a ninguna parte. Los fallos se cuentan en este equipo y nunca salen de él.", "fr" to "Cette version ne signale rien à personne. Les échecs sont comptés sur cette machine et n'en sortent jamais.", "de" to "Dieser Build meldet nirgendwohin. Fehler werden auf diesem Gerät gezählt und verlassen es nie.", "pt" to "Esta compilação não reporta a lado nenhum. As falhas são contadas nesta máquina e nunca saem dela.", "it" to "Questa build non segnala da nessuna parte. Gli errori sono contati su questa macchina e non la lasciano mai.", "ja" to "このビルドはどこにも報告しません。障害はこの端末で数えられ、外に出ることはありません。", "zh" to "此版本不向任何地方报告。故障只在本机计数，绝不外传。", "hi" to "यह बिल्ड कहीं रिपोर्ट नहीं करता। विफलताएँ इसी मशीन पर गिनी जाती हैं और कभी बाहर नहीं जातीं।", "ar" to "لا يُبلّغ هذا الإصدار أي جهة. تُحصى الأعطال على هذا الجهاز ولا تغادره أبدًا."),
        "ncon.disconnect" to mapOf("en" to "Disconnect", "es" to "Desconectar", "fr" to "Déconnecter", "de" to "Trennen", "pt" to "Desligar", "it" to "Scollega", "ja" to "接続解除", "zh" to "断开", "hi" to "अलग करें", "ar" to "فصل"),
        "nrob.snap" to mapOf("en" to "Snapshot", "es" to "Instantánea", "fr" to "Instantané", "de" to "Momentaufnahme", "pt" to "Instantâneo", "it" to "Istantanea", "ja" to "スナップショット", "zh" to "快照", "hi" to "स्नैपशॉट", "ar" to "لقطة"),
        "nrec.hide" to mapOf("en" to "Hide", "es" to "Ocultar", "fr" to "Masquer", "de" to "Ausblenden", "pt" to "Ocultar", "it" to "Nascondi", "ja" to "隠す", "zh" to "隐藏", "hi" to "छिपाएँ", "ar" to "إخفاء"),
        "nfb.title" to mapOf("en" to "Help us improve", "es" to "Ayúdanos a mejorar", "fr" to "Aidez-nous à nous améliorer", "de" to "Hilf uns, besser zu werden", "pt" to "Ajude-nos a melhorar", "it" to "Aiutaci a migliorare", "ja" to "改善に力を貸してください", "zh" to "帮助我们做得更好", "hi" to "हमें बेहतर बनाने में मदद कीजिए", "ar" to "ساعدنا على التحسّن"),
        "nfb.yours" to mapOf("en" to "Yours", "es" to "Lo tuyo", "fr" to "Les vôtres", "de" to "Deine", "pt" to "Os seus", "it" to "I tuoi", "ja" to "あなたの送信分", "zh" to "你发送的", "hi" to "आपके भेजे हुए", "ar" to "ما أرسلته"),
        "prb.title" to mapOf("en" to "When something breaks", "es" to "Cuando algo falla", "fr" to "Quand quelque chose casse", "de" to "Wenn etwas kaputtgeht", "pt" to "Quando algo falha", "it" to "Quando qualcosa si rompe", "ja" to "何かが壊れたとき", "zh" to "出问题的时候", "hi" to "जब कुछ टूटे", "ar" to "حين يتعطّل شيء"),
        "prb.send" to mapOf("en" to "Send counts", "es" to "Enviar los recuentos", "fr" to "Envoyer les décomptes", "de" to "Zählungen senden", "pt" to "Enviar as contagens", "it" to "Invia i conteggi", "ja" to "件数を送る", "zh" to "发送计数", "hi" to "गिनती भेजें", "ar" to "أرسل الأعداد"),
        "prb.donot" to mapOf("en" to "Do not send", "es" to "No enviar", "fr" to "Ne pas envoyer", "de" to "Nicht senden", "pt" to "Não enviar", "it" to "Non inviare", "ja" to "送らない", "zh" to "不要发送", "hi" to "मत भेजें", "ar" to "لا ترسل"),
        "prb.toggle" to mapOf("en" to "Send failure counts", "es" to "Enviar recuentos de fallos", "fr" to "Envoyer les décomptes d'échecs", "de" to "Fehlerzählungen senden", "pt" to "Enviar contagens de falhas", "it" to "Invia i conteggi degli errori", "ja" to "失敗の件数を送る", "zh" to "发送失败计数", "hi" to "विफलताओं की गिनती भेजें", "ar" to "أرسل أعداد الإخفاقات"),
        "prb.owed.none" to mapOf("en" to "Nothing is owed. Either nothing has failed, or everything that has was already reported.", "es" to "No hay nada pendiente. O no ha fallado nada, o todo lo que falló ya se informó.", "fr" to "Rien n'est dû. Soit rien n'a échoué, soit tout ce qui a échoué a déjà été signalé.", "de" to "Es steht nichts aus. Entweder ist nichts fehlgeschlagen, oder alles Fehlgeschlagene wurde bereits gemeldet.", "pt" to "Não há nada em dívida. Ou nada falhou, ou tudo o que falhou já foi reportado.", "it" to "Non c'è nulla in sospeso. O non è fallito nulla, o tutto ciò che è fallito è già stato segnalato.", "ja" to "送るべきものはありません。何も失敗していないか、失敗したものはすべて報告済みです。", "zh" to "没有待发送的内容。要么什么都没失败，要么失败过的都已上报。", "hi" to "कुछ भी बकाया नहीं है। या तो कुछ विफल नहीं हुआ, या जो हुआ वह पहले ही भेजा जा चुका है।", "ar" to "لا شيء معلّق. إما أن شيئًا لم يخفق، وإما أن كل ما أخفق قد أُبلغ عنه سلفًا."),
        "nov.unlocked" to mapOf("en" to "Vault unlocked", "es" to "Bóveda desbloqueada", "fr" to "Coffre déverrouillé", "de" to "Tresor entsperrt", "pt" to "Cofre desbloqueado", "it" to "Cassaforte sbloccata", "ja" to "保管庫を解錠しました", "zh" to "保险库已解锁", "hi" to "वॉल्ट अनलॉक है", "ar" to "الخزنة مفتوحة"),
        "nov.title" to mapOf("en" to "Your vault", "es" to "Tu bóveda", "fr" to "Votre coffre", "de" to "Dein Tresor", "pt" to "O seu cofre", "it" to "La tua cassaforte", "ja" to "あなたの保管庫", "zh" to "你的保险库", "hi" to "आपका वॉल्ट", "ar" to "خزنتك"),
        "nov.sealed" to mapOf("en" to "Records are sealed at rest; every access is hash-chained in the audit log.", "es" to "Los registros están sellados en reposo; cada acceso queda encadenado por hash en el registro de auditoría.", "fr" to "Les enregistrements sont scellés au repos ; chaque accès est chaîné par hachage dans le journal d'audit.", "de" to "Datensätze sind im Ruhezustand versiegelt; jeder Zugriff wird im Audit-Log hash-verkettet.", "pt" to "Os registos estão selados em repouso; cada acesso fica encadeado por hash no registo de auditoria.", "it" to "I record sono sigillati a riposo; ogni accesso è concatenato con hash nel registro di audit.", "ja" to "レコードは保存時に封印され、すべてのアクセスは監査ログにハッシュ連鎖で記録されます。", "zh" to "记录在静态时被封存；每次访问都以哈希链记入审计日志。", "hi" to "रिकॉर्ड विश्राम अवस्था में सील रहते हैं; हर पहुँच ऑडिट लॉग में हैश-श्रृंखला से दर्ज होती है।", "ar" to "السجلات مختومة أثناء التخزين؛ وكل وصول يُسلسل بالتجزئة في سجل التدقيق."),
        "nov.token" to mapOf("en" to "Token", "es" to "Token", "fr" to "Jeton", "de" to "Token", "pt" to "Token", "it" to "Token", "ja" to "トークン", "zh" to "令牌", "hi" to "टोकन", "ar" to "الرمز"),
        "nov.notes" to mapOf("en" to "PDI's explanatory notes arrive in this language; sealed data is untouched.", "es" to "Las notas explicativas de PDI llegan en este idioma; los datos sellados no se tocan.", "fr" to "Les notes explicatives de PDI arrivent dans cette langue ; les données scellées restent intactes.", "de" to "Die erläuternden Hinweise von PDI kommen in dieser Sprache an; versiegelte Daten bleiben unberührt.", "pt" to "As notas explicativas do PDI chegam neste idioma; os dados selados ficam intocados.", "it" to "Le note esplicative di PDI arrivano in questa lingua; i dati sigillati restano intatti.", "ja" to "PDI の説明ノートはこの言語で届きます。封印されたデータには触れません。", "zh" to "PDI 的说明性注释将以此语言送达；封存数据不受影响。", "hi" to "PDI के व्याख्यात्मक नोट इसी भाषा में आते हैं; सीलबंद डेटा अछूता रहता है।", "ar" to "تصل ملاحظات PDI التوضيحية بهذه اللغة؛ وتبقى البيانات المختومة كما هي."),
        "nov.pretrans" to mapOf("en" to "Pre-translate notes", "es" to "Pretraducir las notas", "fr" to "Prétraduire les notes", "de" to "Hinweise vorübersetzen", "pt" to "Pré-traduzir as notas", "it" to "Pre-traduci le note", "ja" to "ノートを事前翻訳", "zh" to "预翻译注释", "hi" to "नोट पहले से अनुवाद करें", "ar" to "ترجمة الملاحظات مسبقًا"),
        "nov.pretrans.off" to mapOf("en" to "Off keeps English notes; sealed data is never touched either way.", "es" to "Desactivado mantiene las notas en inglés; los datos sellados nunca se tocan en ningún caso.", "fr" to "Désactivé garde les notes en anglais ; les données scellées ne sont jamais touchées, dans un cas comme dans l'autre.", "de" to "Aus behält englische Hinweise; versiegelte Daten werden so oder so nie angerührt.", "pt" to "Desligado mantém as notas em inglês; os dados selados nunca são tocados em nenhum dos casos.", "it" to "Disattivato mantiene le note in inglese; i dati sigillati non vengono mai toccati in ogni caso.", "ja" to "オフでは英語のノートのままです。いずれの場合も封印データには触れません。", "zh" to "关闭则保留英文注释；无论开关，封存数据都不会被触碰。", "hi" to "बंद रखने पर नोट अंग्रेज़ी में रहते हैं; दोनों ही स्थितियों में सीलबंद डेटा कभी नहीं छुआ जाता।", "ar" to "الإيقاف يُبقي الملاحظات بالإنجليزية؛ ولا تُمسّ البيانات المختومة في الحالتين."),
        "nov.intact" to mapOf("en" to "Intact", "es" to "Íntegra", "fr" to "Intacte", "de" to "Intakt", "pt" to "Íntegra", "it" to "Integra", "ja" to "正常", "zh" to "完整", "hi" to "अक्षुण्ण", "ar" to "سليمة"),
        "nov.broken" to mapOf("en" to "Broken", "es" to "Rota", "fr" to "Rompue", "de" to "Gebrochen", "pt" to "Quebrada", "it" to "Rotta", "ja" to "破損", "zh" to "已断裂", "hi" to "टूटी हुई", "ar" to "مكسورة"),
        "nadm.title" to mapOf("en" to "Admin · Key management", "es" to "Administración · Gestión de claves", "fr" to "Admin · Gestion des clés", "de" to "Admin · Schlüsselverwaltung", "pt" to "Admin · Gestão de chaves", "it" to "Admin · Gestione delle chiavi", "ja" to "管理 · 鍵の管理", "zh" to "管理 · 密钥管理", "hi" to "एडमिन · कुंजी प्रबंधन", "ar" to "الإدارة · إدارة المفاتيح"),
        "nadm.req" to mapOf("en" to "Requires the deployment's admin token (PDI_ADMIN_TOKEN) — not the tenant token. Kept in memory only, never stored.", "es" to "Requiere el token de administrador del despliegue (PDI_ADMIN_TOKEN), no el token del inquilino. Se guarda solo en memoria, nunca se almacena.", "fr" to "Nécessite le jeton d'administration du déploiement (PDI_ADMIN_TOKEN) — pas le jeton du locataire. Gardé en mémoire seulement, jamais stocké.", "de" to "Erfordert das Admin-Token der Installation (PDI_ADMIN_TOKEN) — nicht das Mandanten-Token. Nur im Speicher gehalten, nie gespeichert.", "pt" to "Requer o token de administrador da instalação (PDI_ADMIN_TOKEN) — não o token do inquilino. Mantido apenas em memória, nunca guardado.", "it" to "Richiede il token di amministrazione dell'installazione (PDI_ADMIN_TOKEN), non il token del tenant. Tenuto solo in memoria, mai salvato.", "ja" to "この環境の管理者トークン（PDI_ADMIN_TOKEN）が必要です — テナントのトークンではありません。メモリ内にのみ保持され、保存されることはありません。", "zh" to "需要此部署的管理员令牌（PDI_ADMIN_TOKEN）——不是租户令牌。仅保存在内存中，绝不落盘。", "hi" to "परिनियोजन का एडमिन टोकन (PDI_ADMIN_TOKEN) चाहिए — टेनेंट टोकन नहीं। केवल मेमोरी में रहता है, कभी संग्रहीत नहीं होता।", "ar" to "يتطلب رمز المشرف الخاص بالنشر (PDI_ADMIN_TOKEN) — لا رمز المستأجر. يُحفظ في الذاكرة فقط ولا يُخزَّن أبدًا."),
        "nadm.req.more" to mapOf("en" to "Rotation re-seals every record; retire deletes non-active versions (safe only after a reseal).", "es" to "La rotación vuelve a sellar todos los registros; retirar elimina las versiones no activas (seguro solo tras un resellado).", "fr" to "La rotation rescelle chaque enregistrement ; le retrait supprime les versions non actives (sûr seulement après un rescellement).", "de" to "Die Rotation versiegelt jeden Datensatz neu; das Zurückziehen löscht nicht aktive Versionen (nur nach einer Neuversiegelung sicher).", "pt" to "A rotação volta a selar todos os registos; retirar apaga as versões não ativas (seguro apenas após um novo selo).", "it" to "La rotazione risigilla ogni record; il ritiro elimina le versioni non attive (sicuro solo dopo una nuova sigillatura).", "ja" to "ローテーションはすべてのレコードを再封印します。廃止は非アクティブなバージョンを削除します（再封印後のみ安全）。", "zh" to "轮换会重新封存所有记录；停用会删除非活动版本（仅在重新封存后才安全）。", "hi" to "घुमाने से हर रिकॉर्ड फिर से सील होता है; हटाने से निष्क्रिय संस्करण मिटते हैं (केवल पुनः सील के बाद सुरक्षित)।", "ar" to "التدوير يعيد ختم كل سجل؛ والسحب يحذف الإصدارات غير النشطة (آمن فقط بعد إعادة الختم)."),
        "naud.desc" to mapOf("en" to "Every vault action is hash-chained. Verify recomputes the whole chain.", "es" to "Cada acción de la bóveda se encadena por hash. Verificar recalcula toda la cadena.", "fr" to "Chaque action du coffre est chaînée par hachage. Vérifier recalcule toute la chaîne.", "de" to "Jede Tresor-Aktion wird hash-verkettet. Die Prüfung berechnet die gesamte Kette neu.", "pt" to "Cada ação do cofre é encadeada por hash. Verificar recalcula toda a cadeia.", "it" to "Ogni azione della cassaforte è concatenata con hash. La verifica ricalcola l'intera catena.", "ja" to "保管庫のすべての操作はハッシュ連鎖されます。検証は連鎖全体を再計算します。", "zh" to "保险库的每次操作都以哈希连成链。验证会重算整条链。", "hi" to "वॉल्ट की हर कार्रवाई हैश-श्रृंखला में जुड़ती है। सत्यापन पूरी श्रृंखला की पुनर्गणना करता है।", "ar" to "كل إجراء في الخزنة يُسلسل بالتجزئة. والتحقق يعيد حساب السلسلة كاملة."),
        "naud.verifying" to mapOf("en" to "Verifying…", "es" to "Verificando…", "fr" to "Vérification…", "de" to "Prüfung läuft…", "pt" to "A verificar…", "it" to "Verifica in corso…", "ja" to "検証中…", "zh" to "正在验证…", "hi" to "सत्यापन हो रहा है…", "ar" to "جارٍ التحقق…"),
        "naud.intact" to mapOf("en" to "Chain intact", "es" to "Cadena íntegra", "fr" to "Chaîne intacte", "de" to "Kette intakt", "pt" to "Cadeia íntegra", "it" to "Catena integra", "ja" to "チェーンは正常です", "zh" to "链条完整", "hi" to "श्रृंखला अक्षुण्ण", "ar" to "السلسلة سليمة"),
        "naud.broken" to mapOf("en" to "Chain broken", "es" to "Cadena rota", "fr" to "Chaîne rompue", "de" to "Kette gebrochen", "pt" to "Cadeia quebrada", "it" to "Catena rotta", "ja" to "チェーンが破損しています", "zh" to "链条已断裂", "hi" to "श्रृंखला टूटी हुई", "ar" to "السلسلة مكسورة"),
        "naud.events" to mapOf("en" to "{n} recorded events", "es" to "{n} eventos registrados", "fr" to "{n} événements enregistrés", "de" to "{n} erfasste Ereignisse", "pt" to "{n} eventos registados", "it" to "{n} eventi registrati", "ja" to "記録済みイベント {n} 件", "zh" to "已记录 {n} 个事件", "hi" to "{n} दर्ज घटनाएँ", "ar" to "{n} أحداث مسجلة"),
        "nfb.sub" to mapOf("en" to "Tell us how to make PDI better — an idea, a rough edge, a bug, or what you love. It goes straight to the team.", "es" to "Cuéntanos cómo mejorar PDI: una idea, algo áspero, un error o lo que te encanta. Va directo al equipo.", "fr" to "Dites-nous comment améliorer PDI — une idée, un point rugueux, un bogue ou ce que vous aimez. Cela va droit à l'équipe.", "de" to "Sag uns, wie PDI besser werden kann — eine Idee, eine raue Kante, ein Fehler oder was dir gefällt. Es geht direkt ans Team.", "pt" to "Diga-nos como tornar o PDI melhor — uma ideia, uma aresta, um erro ou o que adora. Vai direto para a equipa.", "it" to "Dicci come migliorare PDI — un'idea, uno spigolo, un bug o ciò che ami. Arriva dritto al team.", "ja" to "PDI をより良くする方法を教えてください — アイデア、粗い部分、バグ、気に入っている点。そのままチームに届きます。", "zh" to "告诉我们如何让 PDI 更好 — 一个想法、一处粗糙、一个错误，或你喜欢的地方。直达团队。", "hi" to "बताइए PDI को बेहतर कैसे बनाएँ — कोई विचार, खुरदुरा किनारा, बग, या जो आपको पसंद है। सीधे टीम तक जाता है।", "ar" to "أخبرنا كيف نجعل PDI أفضل — فكرة أو جانب خشن أو خلل أو ما تحبه. يصل مباشرة إلى الفريق."),
        "nfb.rating" to mapOf("en" to "Rating", "es" to "Valoración", "fr" to "Note", "de" to "Bewertung", "pt" to "Classificação", "it" to "Valutazione", "ja" to "評価", "zh" to "评分", "hi" to "रेटिंग", "ar" to "التقييم"),
        "nrec.sub" to mapOf("en" to "Store a value — it is sealed at rest with AES-256-GCM.", "es" to "Guarda un valor: se sella en reposo con AES-256-GCM.", "fr" to "Stockez une valeur — elle est scellée au repos avec AES-256-GCM.", "de" to "Speichere einen Wert — er wird im Ruhezustand mit AES-256-GCM versiegelt.", "pt" to "Guarde um valor — é selado em repouso com AES-256-GCM.", "it" to "Conserva un valore — è sigillato a riposo con AES-256-GCM.", "ja" to "値を保存します — 保存時に AES-256-GCM で封印されます。", "zh" to "存入一个值 — 静态时以 AES-256-GCM 封存。", "hi" to "कोई मान रखें — विश्राम अवस्था में AES-256-GCM से सील होता है।", "ar" to "خزّن قيمة — تُختم أثناء التخزين بـ AES-256-GCM."),
        "nrec.none" to mapOf("en" to "No records yet — seal one above.", "es" to "Aún no hay registros: sella uno arriba.", "fr" to "Pas encore d'enregistrements — scellez-en un ci-dessus.", "de" to "Noch keine Datensätze — versiegle oben einen.", "pt" to "Ainda não há registos — sele um acima.", "it" to "Ancora nessun record — sigillane uno qui sopra.", "ja" to "まだレコードがありません — 上で封印してください。", "zh" to "还没有记录 — 在上方封存一条。", "hi" to "अभी कोई रिकॉर्ड नहीं — ऊपर एक सील करें।", "ar" to "لا سجلات بعد — اختم واحدًا أعلاه."),
        "nrec.reveal" to mapOf("en" to "Reveal", "es" to "Revelar", "fr" to "Révéler", "de" to "Aufdecken", "pt" to "Revelar", "it" to "Rivela", "ja" to "表示", "zh" to "显示", "hi" to "दिखाएँ", "ar" to "كشف"),
        "nrec.delete" to mapOf("en" to "Delete", "es" to "Eliminar", "fr" to "Supprimer", "de" to "Löschen", "pt" to "Apagar", "it" to "Elimina", "ja" to "削除", "zh" to "删除", "hi" to "हटाएँ", "ar" to "حذف"),
        "nrec.origin" to mapOf("en" to "Origin: {x}", "es" to "Origen: {x}", "fr" to "Origine : {x}", "de" to "Ursprung: {x}", "pt" to "Origem: {x}", "it" to "Origine: {x}", "ja" to "由来：{x}", "zh" to "来源：{x}", "hi" to "उद्गम: {x}", "ar" to "الأصل: {x}"),
        "nrec.sealedline" to mapOf("en" to "Sealed {date} · {n} ciphertext bytes", "es" to "Sellado {date} · {n} bytes de texto cifrado", "fr" to "Scellé {date} · {n} octets chiffrés", "de" to "Versiegelt {date} · {n} Chiffrat-Bytes", "pt" to "Selado {date} · {n} bytes cifrados", "it" to "Sigillato {date} · {n} byte cifrati", "ja" to "封印 {date} · 暗号文 {n} バイト", "zh" to "封存于 {date} · 密文 {n} 字节", "hi" to "सील {date} · {n} सिफरटेक्स्ट बाइट", "ar" to "خُتم {date} · {n} بايت مشفّر"),
        "nrec.auditline" to mapOf("en" to "{n} audit event(s) · chain {status}", "es" to "{n} evento(s) de auditoría · cadena {status}", "fr" to "{n} événement(s) d'audit · chaîne {status}", "de" to "{n} Audit-Ereignis(se) · Kette {status}", "pt" to "{n} evento(s) de auditoria · cadeia {status}", "it" to "{n} evento/i di audit · catena {status}", "ja" to "監査イベント {n} 件 · チェーン {status}", "zh" to "{n} 个审计事件 · 链 {status}", "hi" to "{n} ऑडिट घटनाएँ · श्रृंखला {status}", "ar" to "{n} أحداث تدقيق · السلسلة {status}"),
        "nrec.chain.ok" to mapOf("en" to "intact ✓", "es" to "íntegra ✓", "fr" to "intacte ✓", "de" to "intakt ✓", "pt" to "íntegra ✓", "it" to "integra ✓", "ja" to "正常 ✓", "zh" to "完整 ✓", "hi" to "अक्षुण्ण ✓", "ar" to "سليمة ✓"),
        "nrec.chain.bad" to mapOf("en" to "BROKEN", "es" to "ROTA", "fr" to "ROMPUE", "de" to "GEBROCHEN", "pt" to "QUEBRADA", "it" to "ROTTA", "ja" to "破損", "zh" to "已断裂", "hi" to "टूटी", "ar" to "مكسورة"),
        "nrob.sub" to mapOf("en" to "What your robots see stays sealed — every intake is encrypted at rest and hash-chained in the audit log.", "es" to "Lo que ven tus robots queda sellado: cada entrada se cifra en reposo y se encadena por hash en el registro de auditoría.", "fr" to "Ce que voient vos robots reste scellé — chaque entrée est chiffrée au repos et chaînée par hachage dans le journal d'audit.", "de" to "Was deine Roboter sehen, bleibt versiegelt — jede Aufnahme wird im Ruhezustand verschlüsselt und im Audit-Log hash-verkettet.", "pt" to "O que os seus robôs veem fica selado — cada entrada é cifrada em repouso e encadeada por hash no registo de auditoria.", "it" to "Ciò che vedono i tuoi robot resta sigillato — ogni acquisizione è cifrata a riposo e concatenata con hash nel registro di audit.", "ja" to "ロボットが見たものは封印されたままです — すべての取り込みは保存時に暗号化され、監査ログにハッシュ連鎖で記録されます。", "zh" to "你的机器人所见都被封存 — 每次采集都在静态加密，并以哈希链记入审计日志。", "hi" to "आपके रोबोट जो देखते हैं वह सील रहता है — हर इनटेक विश्राम में एन्क्रिप्ट होता है और ऑडिट लॉग में हैश-श्रृंखला से जुड़ता है।", "ar" to "ما تراه روبوتاتك يبقى مختومًا — كل التقاط يُشفَّر أثناء التخزين ويُسلسل بالتجزئة في سجل التدقيق."),
        "nrob.bind" to mapOf("en" to "Bind a robot", "es" to "Vincular un robot", "fr" to "Associer un robot", "de" to "Einen Roboter verbinden", "pt" to "Vincular um robô", "it" to "Collega un robot", "ja" to "ロボットを接続", "zh" to "绑定一台机器人", "hi" to "एक रोबोट जोड़ें", "ar" to "اربط روبوتًا"),
        "nrob.sealed" to mapOf("en" to "Sealed", "es" to "Sellado", "fr" to "Scellé", "de" to "Versiegelt", "pt" to "Selado", "it" to "Sigillato", "ja" to "封印済み", "zh" to "已封存", "hi" to "सील हो गया", "ar" to "مختوم"),
        "nrob.count" to mapOf("en" to "{n} sealed", "es" to "{n} sellados", "fr" to "{n} scellés", "de" to "{n} versiegelt", "pt" to "{n} selados", "it" to "{n} sigillati", "ja" to "封印済み {n} 件", "zh" to "已封存 {n} 项", "hi" to "{n} सील किए गए", "ar" to "{n} مختومة"),
        "nrob.read" to mapOf("en" to "Read it (audited) via Vault → the key above.", "es" to "Léelo (auditado) en Bóveda → la clave de arriba.", "fr" to "Lisez-le (audité) via Coffre → la clé ci-dessus.", "de" to "Lies es (auditiert) über Tresor → den Schlüssel oben.", "pt" to "Leia-o (auditado) em Cofre → a chave acima.", "it" to "Leggilo (con audit) da Cassaforte → la chiave qui sopra.", "ja" to "保管庫 → 上のキーから（監査付きで）読めます。", "zh" to "经保险库 → 上方键名读取（有审计）。", "hi" to "वॉल्ट → ऊपर की कुंजी से (ऑडिट सहित) पढ़ें।", "ar" to "اقرأه (بتدقيق) عبر الخزنة → المفتاح أعلاه."),
        "nrob.readone" to mapOf("en" to "Read one (audited) via Vault → the key above.", "es" to "Lee uno (auditado) en Bóveda → la clave de arriba.", "fr" to "Lisez-en un (audité) via Coffre → la clé ci-dessus.", "de" to "Lies einen (auditiert) über Tresor → den Schlüssel oben.", "pt" to "Leia um (auditado) em Cofre → a chave acima.", "it" to "Leggine uno (con audit) da Cassaforte → la chiave qui sopra.", "ja" to "保管庫 → 上のキーから（監査付きで）1 件読めます。", "zh" to "经保险库 → 上方键名读取一项（有审计）。", "hi" to "वॉल्ट → ऊपर की कुंजी से एक (ऑडिट सहित) पढ़ें।", "ar" to "اقرأ واحدًا (بتدقيق) عبر الخزنة → المفتاح أعلاه."),
        "nrob.none" to mapOf("en" to "Nothing sealed yet.", "es" to "Aún no hay nada sellado.", "fr" to "Rien de scellé pour l'instant.", "de" to "Noch nichts versiegelt.", "pt" to "Ainda nada selado.", "it" to "Ancora nulla di sigillato.", "ja" to "まだ何も封印されていません。", "zh" to "尚未封存任何内容。", "hi" to "अभी कुछ भी सील नहीं हुआ।", "ar" to "لم يُختم شيء بعد."),
        "nrob.keys" to mapOf("en" to "Sealed keys", "es" to "Claves selladas", "fr" to "Clés scellées", "de" to "Versiegelte Schlüssel", "pt" to "Chaves seladas", "it" to "Chiavi sigillate", "ja" to "封印済みキー", "zh" to "已封存的键", "hi" to "सील की गई कुंजियाँ", "ar" to "مفاتيح مختومة"),
        "nrob.map" to mapOf("en" to "Seal map", "es" to "Sellar el mapa", "fr" to "Sceller la carte", "de" to "Karte versiegeln", "pt" to "Selar o mapa", "it" to "Sigilla la mappa", "ja" to "地図を封印", "zh" to "封存地图", "hi" to "नक्शा सील करें", "ar" to "ختم الخريطة"),
        "nrob.log" to mapOf("en" to "Sensor log", "es" to "Registro de sensores", "fr" to "Journal des capteurs", "de" to "Sensorprotokoll", "pt" to "Registo de sensores", "it" to "Registro dei sensori", "ja" to "センサーログ", "zh" to "传感器日志", "hi" to "सेंसर लॉग", "ar" to "سجل المستشعرات"),
        "ncon.sub" to mapOf("en" to "Link a platform account. Collected content is sealed into the vault; every ingest is hash-chained in the audit log.", "es" to "Vincula una cuenta de plataforma. El contenido recogido se sella en la bóveda; cada ingesta se encadena por hash en el registro de auditoría.", "fr" to "Associez un compte de plateforme. Le contenu collecté est scellé dans le coffre ; chaque ingestion est chaînée par hachage dans le journal d'audit.", "de" to "Verknüpfe ein Plattform-Konto. Gesammelte Inhalte werden im Tresor versiegelt; jede Aufnahme wird im Audit-Log hash-verkettet.", "pt" to "Vincule uma conta de plataforma. O conteúdo recolhido é selado no cofre; cada ingestão fica encadeada por hash no registo de auditoria.", "it" to "Collega un account di piattaforma. I contenuti raccolti sono sigillati nella cassaforte; ogni acquisizione è concatenata con hash nel registro di audit.", "ja" to "プラットフォームのアカウントを連携します。収集されたコンテンツは保管庫に封印され、すべての取り込みは監査ログにハッシュ連鎖で記録されます。", "zh" to "关联一个平台账户。采集的内容封存进保险库；每次摄取都以哈希链记入审计日志。", "hi" to "कोई प्लेटफ़ॉर्म खाता जोड़ें। एकत्र सामग्री वॉल्ट में सील होती है; हर इनजेस्ट ऑडिट लॉग में हैश-श्रृंखला से जुड़ता है।", "ar" to "اربط حساب منصة. يُختم المحتوى المجموع في الخزنة؛ وكل إدخال يُسلسل بالتجزئة في سجل التدقيق."),
        "ncon.collect" to mapOf("en" to "Connect to collect", "es" to "Conectar para recoger", "fr" to "Connecter pour collecter", "de" to "Zum Sammeln verbinden", "pt" to "Ligar para recolher", "it" to "Connetti per raccogliere", "ja" to "収集のために接続", "zh" to "连接以采集", "hi" to "एकत्र करने के लिए जोड़ें", "ar" to "اتصال للجمع"),
        "ncon.publish" to mapOf("en" to "Connect to publish", "es" to "Conectar para publicar", "fr" to "Connecter pour publier", "de" to "Zum Veröffentlichen verbinden", "pt" to "Ligar para publicar", "it" to "Connetti per pubblicare", "ja" to "公開のために接続", "zh" to "连接以发布", "hi" to "प्रकाशित करने के लिए जोड़ें", "ar" to "اتصال للنشر"),
        "ncon.scrape" to mapOf("en" to "Fetch the page", "es" to "Traer la página", "fr" to "Récupérer la page", "de" to "Die Seite holen", "pt" to "Buscar a página", "it" to "Recupera la pagina", "ja" to "ページを取得", "zh" to "抓取页面", "hi" to "पेज लाएँ", "ar" to "جلب الصفحة"),
        "ncon.ingest" to mapOf("en" to "Ingest sample", "es" to "Ingerir una muestra", "fr" to "Ingérer un échantillon", "de" to "Probe aufnehmen", "pt" to "Ingerir uma amostra", "it" to "Acquisisci un campione", "ja" to "サンプルを取り込む", "zh" to "摄取样本", "hi" to "नमूना लें", "ar" to "التقاط عيّنة"),
        "ncon.update" to mapOf("en" to "Publish update", "es" to "Publicar una actualización", "fr" to "Publier une mise à jour", "de" to "Update veröffentlichen", "pt" to "Publicar uma atualização", "it" to "Pubblica un aggiornamento", "ja" to "更新を公開", "zh" to "发布更新", "hi" to "अपडेट प्रकाशित करें", "ar" to "نشر تحديث"),
        "ntr.retained" to mapOf("en" to "retained until {date}", "es" to "retenido hasta {date}", "fr" to "conservé jusqu'au {date}", "de" to "aufbewahrt bis {date}", "pt" to "retido até {date}", "it" to "conservato fino al {date}", "ja" to "{date} まで保持", "zh" to "保留至 {date}", "hi" to "{date} तक प्रतिधारित", "ar" to "محتفظ به حتى {date}"),
        "nadm.dsr" to mapOf("en" to "What do you hold about us", "es" to "Qué guardáis sobre nosotros", "fr" to "Que détenez-vous sur nous", "de" to "Was haltet ihr über uns", "pt" to "O que guardam sobre nós", "it" to "Cosa conservate su di noi", "ja" to "私たちについて何を保持していますか", "zh" to "你们保存了我们的什么", "hi" to "आप हमारे बारे में क्या रखते हैं", "ar" to "ماذا تحتفظون عنا"),
        "tab.robots" to mapOf("en" to "Robots", "es" to "Robots", "fr" to "Robots", "de" to "Roboter", "pt" to "Robôs", "it" to "Robot", "ja" to "ロボット", "zh" to "机器人", "hi" to "रोबोट", "ar" to "روبوتات"),
        "tab.connectors" to mapOf("en" to "Connectors", "es" to "Conectores", "fr" to "Connecteurs", "de" to "Konnektoren", "pt" to "Conectores", "it" to "Connettori", "ja" to "コネクタ", "zh" to "连接器", "hi" to "कनेक्टर", "ar" to "الموصلات"),
        "tab.overview" to mapOf(
            "en" to "Overview", "es" to "Resumen", "fr" to "Aperçu",
            "de" to "Übersicht", "pt" to "Visão geral", "it" to "Panoramica",
            "ja" to "概要", "zh" to "概览", "hi" to "अवलोकन", "ar" to "نظرة عامة"),
        "tab.vault" to mapOf(
            "en" to "Vault", "es" to "Bóveda", "fr" to "Coffre",
            "de" to "Tresor", "pt" to "Cofre", "it" to "Cassaforte",
            "ja" to "保管庫", "zh" to "保险库", "hi" to "वॉल्ट", "ar" to "الخزنة"),
        "tab.audit" to mapOf(
            "en" to "Audit", "es" to "Auditoría", "fr" to "Audit",
            "de" to "Audit", "pt" to "Auditoria", "it" to "Audit",
            "ja" to "監査", "zh" to "审计", "hi" to "ऑडिट", "ar" to "تدقيق"),
        "tab.sources" to mapOf(
            "en" to "Sources", "es" to "Fuentes", "fr" to "Sources",
            "de" to "Quellen", "pt" to "Fontes", "it" to "Fonti",
            "ja" to "ソース", "zh" to "来源", "hi" to "स्रोत", "ar" to "المصادر"),
        "tab.transfers" to mapOf(
            "en" to "Transfers", "es" to "Transferencias", "fr" to "Transferts",
            "de" to "Übertragungen", "pt" to "Transferências", "it" to "Trasferimenti",
            "ja" to "転送", "zh" to "传输", "hi" to "स्थानांतरण", "ar" to "التحويلات"),
        "action.sign_out" to mapOf(
            "en" to "Sign out", "es" to "Cerrar sesión", "fr" to "Se déconnecter",
            "de" to "Abmelden", "pt" to "Sair", "it" to "Esci",
            "ja" to "サインアウト", "zh" to "退出登录", "hi" to "साइन आउट",
            "ar" to "تسجيل الخروج"),
    )
}
